using EntityFrameworkCore.Projectables;
using Microsoft.EntityFrameworkCore;
using ProjectWarehouse.Server.Infrastructure;

namespace ProjectWarehouse.Server.Domain;

public class Order : IHasIdentity
{
    public Guid Id { get; set; }

    /// <summary>Auto-incremented order number generated by the database sequence.</summary>
    public int Number { get; set; }

    public OrderType Type { get; set; }
    public OrderStatus Status { get; set; } = OrderStatus.Draft;

    /// <summary>
    /// The order exists on the marketplace but never passed through WMS: it is not assembled, deducts no
    /// stock, and carries no fulfillments. <see cref="Status"/> is <see cref="OrderStatus.Canceled"/> when the
    /// goods never left the seller and <see cref="OrderStatus.Shipped"/> otherwise; the finer marketplace
    /// state lives in <see cref="MarketplaceOrder.Status"/>.
    /// </summary>
    public bool IsExternal { get; set; }

    public string? Notes { get; set; }
    public DateTime? PlannedShipmentAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? ConfirmedAt { get; set; }
    public DateTime? AssemblyStartedAt { get; set; }
    public DateTime? AssembledAt { get; set; }
    public DateTime? ShippedAt { get; set; }
    public DateTime? CanceledAt { get; set; }

    /// <summary>Required for every order WMS works on; null only for <see cref="IsExternal"/> ones.</summary>
    public Guid? WarehouseId { get; set; }
    public Warehouse? Warehouse { get; set; }

    public Guid? CreatedById { get; set; }
    public ApplicationUser? CreatedBy { get; set; }

    /// <summary>Marketplace side of the order; null for Direct. Shares this order's primary key.</summary>
    public MarketplaceOrder? MarketplaceOrder { get; set; }

    public ICollection<OrderMarketplaceItem> MarketplaceItems { get; set; } = [];

    /// <summary>Every return the marketplace reported for this posting, cancellations included.</summary>
    public ICollection<MarketplaceReturn> MarketplaceReturns { get; set; } = [];
    public ICollection<OrderBox> Boxes { get; set; } = [];
    public ICollection<AssemblyTask> AssemblyTasks { get; set; } = [];
    public List<OrderImage> Images { get; set; } = [];

    public ICollection<OrderTag> Tags { get; set; } = [];

    /// <summary>
    /// The posting's own date comes before <see cref="CreatedAt"/>: for an imported order that is the import
    /// moment, and a cancelled external FBO posting has neither a shipment date nor <see cref="ShippedAt"/>.
    /// </summary>
    [Projectable]
    public DateTime EffectiveDate => PlannedShipmentAt ?? ShippedAt ?? AssembledAt
        ?? (MarketplaceOrder != null ? MarketplaceOrder.InProcessAt : null) ?? CreatedAt;
    
    /// <summary>Units that actually came back — see <see cref="MarketplaceReturn.IsCountedAsReturn"/>.</summary>
    [Projectable]
    public int ReturnedQuantity => MarketplaceReturns.Where(r => r.IsCountedAsReturn).Sum(r => r.Quantity);

    [Projectable]
    public int MarketplaceQuantity => MarketplaceItems.Sum(i => i.Quantity);

    /// <summary>Which step is late once <see cref="PlannedShipmentAt"/> has passed; null when nothing is late.</summary>
    [Projectable]
    public OrderOverdueKind? OverdueKindAt(DateTime now) =>
        PlannedShipmentAt == null || PlannedShipmentAt >= now ? (OrderOverdueKind?)null
        : Status == OrderStatus.Draft || Status == OrderStatus.Confirmed || Status == OrderStatus.Assembly
            ? OrderOverdueKind.Assembly
        : Status == OrderStatus.Assembled ? OrderOverdueKind.Shipment
        : null;

    [Projectable]
    public bool TerminalStatus => Status == OrderStatus.Shipped || Status == OrderStatus.Assembled || Status == OrderStatus.Canceled;

    // The ternary is load-bearing: SearchExtensions splices this body straight into EF.Functions.ILike,
    // and ILIKE(NULL, …) is NULL — a bare concatenation would drop every Direct and FBO order from search.
    [Projectable]
    public string SearchString =>
        Number + " " + Notes + " "
        + (MarketplaceOrder != null
            ? MarketplaceOrder.PostingNumber + " " + (MarketplaceOrder.ScanitBarcode ?? "")
            : "");

    /// <summary>
    /// Search over the order plus its contents — box labels, box component catalog items, marketplace item
    /// cards. Not used by global search. Call through <c>WhereMatchesExtendedSearch</c>.
    /// </summary>
    [Projectable]
    public bool MatchesExtendedSearch(string pattern) =>
        EF.Functions.ILike(SearchString, pattern, SearchExtensions.EscapeChar)
        || Boxes.Any(b => EF.Functions.ILike(b.Label ?? "", pattern, SearchExtensions.EscapeChar))
        || Boxes.Any(b => b.Components.Any(c =>
            EF.Functions.ILike(c.CatalogItem.SearchString, pattern, SearchExtensions.EscapeChar)))
        || MarketplaceItems.Any(i => i.MarketplaceCard != null
            && EF.Functions.ILike(i.MarketplaceCard.SearchString, pattern, SearchExtensions.EscapeChar));
}
