using EntityFrameworkCore.Projectables;
using ProjectWarehouse.Server.Infrastructure;

namespace ProjectWarehouse.Server.Domain;

public class Order : IHasIdentity
{
    public Guid Id { get; set; }

    /// <summary>Auto-incremented order number generated by the database sequence.</summary>
    public int Number { get; set; }

    public OrderType Type { get; set; }
    public OrderStatus Status { get; set; } = OrderStatus.Draft;

    public string? Notes { get; set; }
    public DateTime? PlannedShipmentAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public Guid WarehouseId { get; set; }
    public Warehouse Warehouse { get; set; } = null!;

    public Guid? CreatedById { get; set; }
    public ApplicationUser? CreatedBy { get; set; }

    /// <summary>Marketplace side of the order; null for Direct. Shares this order's primary key.</summary>
    public MarketplaceOrder? MarketplaceOrder { get; set; }

    public ICollection<OrderMarketplaceItem> MarketplaceItems { get; set; } = [];
    public ICollection<OrderBox> Boxes { get; set; } = [];
    public ICollection<AssemblyTask> AssemblyTasks { get; set; } = [];

    // The ternary is load-bearing: SearchExtensions splices this body straight into EF.Functions.ILike,
    // and ILIKE(NULL, …) is NULL — a bare concatenation would drop every Direct and FBO order from search.
    [Projectable]
    public string SearchString =>
        Number + " " + Notes + " " + (MarketplaceOrder != null ? MarketplaceOrder.PostingNumber : "");
}
