using EntityFrameworkCore.Projectables;
using ProjectWarehouse.Server.Infrastructure;

namespace ProjectWarehouse.Server.Domain;

public class Receipt : IHasIdentity
{
    public Guid Id { get; set; }

    /// <summary>Auto-incremented receipt number generated by the database sequence.</summary>
    public int Number { get; set; }

    public string? Name { get; set; }
    public ReceiptReason Reason { get; set; }
    public ReceiptStatus Status { get; set; } = ReceiptStatus.Draft;
    public string? Notes { get; set; }
    public DateOnly? PlannedDeliveryDate { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>When processing first began; kept when reverted to Planned, overwritten on the next start.</summary>
    public DateTime? StartedAt { get; set; }
    public DateTime? FinishedAt { get; set; }
    public DateTime? CanceledAt { get; set; }

    public Guid WarehouseId { get; set; }
    public Warehouse Warehouse { get; set; } = null!;

    public Guid? CreatedById { get; set; }
    public ApplicationUser? CreatedBy { get; set; }

    public ICollection<ReceiptItem> Items { get; set; } = [];

    public ICollection<ReceiptTag> Tags { get; set; } = [];

    public List<ReceiptImage> Images { get; set; } = [];

    [Projectable]
    public string SearchString => Number + " " +  Name + " " + Notes;
}
