using EntityFrameworkCore.Projectables;
using ProjectWarehouse.Server.Infrastructure;

namespace ProjectWarehouse.Server.Domain;

public class Stocktake : IHasIdentity
{
    public Guid Id { get; set; }

    /// <summary>Auto-incremented stocktake number generated by the database sequence.</summary>
    public int Number { get; set; }

    public string? Name { get; set; }
    public StocktakeStatus Status { get; set; } = StocktakeStatus.Draft;
    public string? Notes { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? StartedAt { get; set; }
    public DateTime? FinishedAt { get; set; }

    public Guid WarehouseId { get; set; }
    public Warehouse Warehouse { get; set; } = null!;

    public Guid? CreatedById { get; set; }
    public ApplicationUser? CreatedBy { get; set; }

    /// <summary>The storage nodes being counted. Scope lives here rather than on the items so that a
    /// node counted as empty is still part of the document.</summary>
    public ICollection<StocktakeNode> Nodes { get; set; } = [];

    [Projectable]
    public string SearchString => Number + " " + Name + " " + Notes;
}
