using EntityFrameworkCore.Projectables;
using ProjectWarehouse.Server.Infrastructure;

namespace ProjectWarehouse.Server.Domain;

public class Writeoff : IHasIdentity
{
    public Guid Id { get; set; }

    /// <summary>Auto-incremented write-off number generated by the database sequence.</summary>
    public int Number { get; set; }

    public string Name { get; set; } = null!;
    public WriteoffReason Reason { get; set; }
    public WriteoffStatus Status { get; set; } = WriteoffStatus.Draft;
    public string? Notes { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public Guid WarehouseId { get; set; }
    public Warehouse Warehouse { get; set; } = null!;

    public Guid? CreatedById { get; set; }
    public ApplicationUser? CreatedBy { get; set; }

    public ICollection<WriteoffItem> Items { get; set; } = [];

    [Projectable]
    public string SearchString => Number + " " + Name + " " + Notes;
}
