using EntityFrameworkCore.Projectables;
using Microsoft.EntityFrameworkCore;
using ProjectWarehouse.Server.Infrastructure;

namespace ProjectWarehouse.Server.Domain;

public class Writeoff : ITaggedWarehouseDocument<WriteoffTag>
{
    public Guid Id { get; set; }

    /// <summary>Auto-incremented write-off number generated by the database sequence.</summary>
    public int Number { get; set; }

    public string? Name { get; set; }
    public WriteoffReason Reason { get; set; }
    public WriteoffStatus Status { get; set; } = WriteoffStatus.Draft;
    public string? Notes { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? FinishedAt { get; set; }
    public DateTime? CanceledAt { get; set; }

    public Guid WarehouseId { get; set; }
    public Warehouse Warehouse { get; set; } = null!;

    public Guid? CreatedById { get; set; }
    public ApplicationUser? CreatedBy { get; set; }

    public ICollection<WriteoffItem> Items { get; set; } = [];

    public ICollection<WriteoffTag> Tags { get; set; } = [];

    public List<WriteoffImage> Images { get; set; } = [];

    [Projectable]
    public string SearchString => Number + " " + Name + " " + Notes;

    /// <summary>
    /// Search over the write-off plus its lines — the catalog item of a standard line, the unit's catalog item
    /// and inventory number of a unit line. Not used by global search. Call through <c>WhereMatchesExtendedSearch</c>.
    /// </summary>
    [Projectable]
    public bool MatchesExtendedSearch(string pattern) =>
        EF.Functions.ILike(SearchString, pattern, SearchExtensions.EscapeChar)
        || Items.Any(i => i.CatalogItem != null
            && EF.Functions.ILike(i.CatalogItem.SearchString, pattern, SearchExtensions.EscapeChar))
        || Items.Any(i => i.UnitInventoryItem != null
            && (EF.Functions.ILike(i.UnitInventoryItem.CatalogItem.SearchString, pattern, SearchExtensions.EscapeChar)
                || EF.Functions.ILike(i.UnitInventoryItem.InventoryNumber ?? "", pattern, SearchExtensions.EscapeChar)));
}
