// This file is auto-generated by @hey-api/openapi-ts

import type {Client, Options as Options2, TDataShape} from "./client";
import {client} from "./client.gen";
import type {
  AuthChangeOwnPasswordData,
  AuthChangeOwnPasswordErrors,
  AuthChangeOwnPasswordResponses,
  AuthLoginData,
  AuthLoginErrors,
  AuthLoginResponses,
  AuthLogoutData,
  AuthLogoutErrors,
  AuthLogoutResponses,
  AuthMeData,
  AuthMeErrors,
  AuthMeResponses,
  AuthRefreshData,
  AuthRefreshErrors,
  AuthRefreshResponses,
  CatalogCreateData,
  CatalogCreateErrors,
  CatalogCreateResponses,
  CatalogCreateTagData,
  CatalogCreateTagErrors,
  CatalogCreateTagResponses,
  CatalogDeleteData,
  CatalogDeleteErrors,
  CatalogDeleteResponses,
  CatalogGetAllData,
  CatalogGetAllErrors,
  CatalogGetAllResponses,
  CatalogGetByIdData,
  CatalogGetByIdErrors,
  CatalogGetByIdResponses,
  CatalogGetForSelectData,
  CatalogGetForSelectErrors,
  CatalogGetForSelectResponses,
  CatalogGetTagsData,
  CatalogGetTagsErrors,
  CatalogGetTagsResponses,
  CatalogUpdateData,
  CatalogUpdateErrors,
  CatalogUpdateResponses,
  ChangelogGetAllData,
  ChangelogGetAllErrors,
  ChangelogGetAllResponses,
  CommonContentGetHomePageContentData,
  CommonContentGetHomePageContentErrors,
  CommonContentGetHomePageContentResponses,
  CommonContentGlobalSearchData,
  CommonContentGlobalSearchErrors,
  CommonContentGlobalSearchResponses,
  InventoryItemsGetAllAssembledBundlesData,
  InventoryItemsGetAllAssembledBundlesErrors,
  InventoryItemsGetAllAssembledBundlesResponses,
  InventoryItemsGetAllData,
  InventoryItemsGetAllErrors,
  InventoryItemsGetAllResponses,
  InventoryItemsGetAllUnitsData,
  InventoryItemsGetAllUnitsErrors,
  InventoryItemsGetAllUnitsResponses,
  PermissionsGetAllData,
  PermissionsGetAllErrors,
  PermissionsGetAllResponses,
  ReceiptsAddAssembledBundlePlacementData,
  ReceiptsAddAssembledBundlePlacementErrors,
  ReceiptsAddAssembledBundlePlacementResponses,
  ReceiptsAddStandardPlacementData,
  ReceiptsAddStandardPlacementErrors,
  ReceiptsAddStandardPlacementResponses,
  ReceiptsAddUnitPlacementData,
  ReceiptsAddUnitPlacementErrors,
  ReceiptsAddUnitPlacementResponses,
  ReceiptsCancelData,
  ReceiptsCancelErrors,
  ReceiptsCancelResponses,
  ReceiptsCreateData,
  ReceiptsCreateErrors,
  ReceiptsCreateResponses,
  ReceiptsDeleteData,
  ReceiptsDeleteErrors,
  ReceiptsDeletePlacementData,
  ReceiptsDeletePlacementErrors,
  ReceiptsDeletePlacementResponses,
  ReceiptsDeleteResponses,
  ReceiptsFinishData,
  ReceiptsFinishErrors,
  ReceiptsFinishResponses,
  ReceiptsGetAllData,
  ReceiptsGetAllErrors,
  ReceiptsGetAllResponses,
  ReceiptsGetByIdData,
  ReceiptsGetByIdErrors,
  ReceiptsGetByIdResponses,
  ReceiptsPlanData,
  ReceiptsPlanErrors,
  ReceiptsPlanResponses,
  ReceiptsRevertData,
  ReceiptsRevertErrors,
  ReceiptsRevertResponses,
  ReceiptsStartProcessingData,
  ReceiptsStartProcessingErrors,
  ReceiptsStartProcessingResponses,
  ReceiptsSyncItemsData,
  ReceiptsSyncItemsErrors,
  ReceiptsSyncItemsResponses,
  ReceiptsUpdateData,
  ReceiptsUpdateErrors,
  ReceiptsUpdateReceivedCountData,
  ReceiptsUpdateReceivedCountErrors,
  ReceiptsUpdateReceivedCountResponses,
  ReceiptsUpdateResponses,
  RolesGetAllData,
  RolesGetAllErrors,
  RolesGetAllResponses,
  RolesGetByIdData,
  RolesGetByIdErrors,
  RolesGetByIdResponses,
  RolesSearchData,
  RolesSearchErrors,
  RolesSearchResponses,
  RolesUpdateAllData,
  RolesUpdateAllErrors,
  RolesUpdateAllResponses,
  StoragePlacesAddNodeData,
  StoragePlacesAddNodeErrors,
  StoragePlacesAddNodeResponses,
  StoragePlacesDeleteNodeData,
  StoragePlacesDeleteNodeErrors,
  StoragePlacesDeleteNodeResponses,
  StoragePlacesGetNodeDetailsData,
  StoragePlacesGetNodeDetailsErrors,
  StoragePlacesGetNodeDetailsResponses,
  StoragePlacesGetNodesData,
  StoragePlacesGetNodesErrors,
  StoragePlacesGetNodesResponses,
  StoragePlacesReorderNodesData,
  StoragePlacesReorderNodesErrors,
  StoragePlacesReorderNodesResponses,
  StoragePlacesUpdateNodeData,
  StoragePlacesUpdateNodeErrors,
  StoragePlacesUpdateNodeResponses,
  UsersChangePasswordData,
  UsersChangePasswordErrors,
  UsersChangePasswordResponses,
  UsersCreateData,
  UsersCreateErrors,
  UsersCreateResponses,
  UsersDeleteData,
  UsersDeleteErrors,
  UsersDeleteResponses,
  UsersGetAllData,
  UsersGetAllErrors,
  UsersGetAllResponses,
  UsersGetByIdData,
  UsersGetByIdErrors,
  UsersGetByIdResponses,
  UsersUpdateData,
  UsersUpdateErrors,
  UsersUpdateResponses,
  WarehousesCreateData,
  WarehousesCreateErrors,
  WarehousesCreateResponses,
  WarehousesDeleteData,
  WarehousesDeleteErrors,
  WarehousesDeleteResponses,
  WarehousesGetAllData,
  WarehousesGetAllErrors,
  WarehousesGetAllResponses,
  WarehousesGetByIdData,
  WarehousesGetByIdErrors,
  WarehousesGetByIdForPrintData,
  WarehousesGetByIdForPrintErrors,
  WarehousesGetByIdForPrintResponses,
  WarehousesGetByIdResponses,
  WarehousesUpdateData,
  WarehousesUpdateErrors,
  WarehousesUpdateResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Authenticate with username and password.
 */
export const authLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh an access token using a valid refresh token.
 */
export const authRefresh = <ThrowOnError extends boolean = false>(
  options: Options<AuthRefreshData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError>({
    url: "/api/auth/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Revoke the current refresh token (logout).
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options: Options<AuthLogoutData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError>({
    url: "/api/auth/logout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Change the current user's own password (requires current password).
 */
export const authChangeOwnPassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthChangeOwnPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    AuthChangeOwnPasswordResponses,
    AuthChangeOwnPasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get the currently authenticated user's info, roles and permissions.
 */
export const authMe = <ThrowOnError extends boolean = false>(
  options?: Options<AuthMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AuthMeResponses, AuthMeErrors, ThrowOnError>({
    url: "/api/auth/me",
    ...options,
  });

/**
 * List all catalog item tags, optionally filtered by name.
 */
export const catalogGetTags = <ThrowOnError extends boolean = false>(
  options?: Options<CatalogGetTagsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<CatalogGetTagsResponses, CatalogGetTagsErrors, ThrowOnError>({
    url: "/api/catalog/tags",
    ...options,
  });

/**
 * Create a new catalog item tag.
 */
export const catalogCreateTag = <ThrowOnError extends boolean = false>(
  options: Options<CatalogCreateTagData, ThrowOnError>,
) =>
  (options.client ?? client).post<CatalogCreateTagResponses, CatalogCreateTagErrors, ThrowOnError>({
    url: "/api/catalog/tags",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all catalog items (paginated, optionally filtered by name).
 */
export const catalogGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<CatalogGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<CatalogGetAllResponses, CatalogGetAllErrors, ThrowOnError>({
    url: "/api/catalog",
    ...options,
  });

/**
 * Create a new catalog item.
 */
export const catalogCreate = <ThrowOnError extends boolean = false>(
  options: Options<CatalogCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<CatalogCreateResponses, CatalogCreateErrors, ThrowOnError>({
    url: "/api/catalog",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a flat list of catalog items for use in select/autocomplete controls.
 *
 * Returns at most 50 items. Excludes product-group children. Optionally filtered by types.
 */
export const catalogGetForSelect = <ThrowOnError extends boolean = false>(
  options?: Options<CatalogGetForSelectData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CatalogGetForSelectResponses,
    CatalogGetForSelectErrors,
    ThrowOnError
  >({url: "/api/catalog/for-select", ...options});

/**
 * Delete a catalog item.
 *
 * Returns 409 `catalogItemIsInUse` if the item is currently stored in any warehouse.
 */
export const catalogDelete = <ThrowOnError extends boolean = false>(
  options: Options<CatalogDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<CatalogDeleteResponses, CatalogDeleteErrors, ThrowOnError>({
    url: "/api/catalog/{id}",
    ...options,
  });

/**
 * Get a catalog item by ID.
 */
export const catalogGetById = <ThrowOnError extends boolean = false>(
  options: Options<CatalogGetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<CatalogGetByIdResponses, CatalogGetByIdErrors, ThrowOnError>({
    url: "/api/catalog/{id}",
    ...options,
  });

/**
 * Update a catalog item.
 *
 *     Assembled bundles are immutable and cannot be updated (returns 422).
 * Type-specific fields:
 * * Standard / Unit: groupId, variationIds (full replace)
 * * Variation: memberIds (full replace)
 * * Bundle: components — id: null creates, id present updates, missing existing entries are deleted
 */
export const catalogUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CatalogUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<CatalogUpdateResponses, CatalogUpdateErrors, ThrowOnError>({
    url: "/api/catalog/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List changelog entries (paginated).
 *
 * Query params: `page` (default 1), `pageSize` (default 20, max 200),
 * `entityType` (optional), `changeLogEntryType` (optional).
 * Returns `Paginated&lt;ChangeLogEntryDto&gt;` ordered by `createdAt` descending.
 */
export const changelogGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<ChangelogGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ChangelogGetAllResponses, ChangelogGetAllErrors, ThrowOnError>({
    url: "/api/changelog",
    ...options,
  });

/**
 * Get list of AppEntities for home page.
 */
export const commonContentGetHomePageContent = <ThrowOnError extends boolean = false>(
  options?: Options<CommonContentGetHomePageContentData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CommonContentGetHomePageContentResponses,
    CommonContentGetHomePageContentErrors,
    ThrowOnError
  >({url: "/api/commoncontent", ...options});

/**
 * Global search for entities.
 */
export const commonContentGlobalSearch = <ThrowOnError extends boolean = false>(
  options?: Options<CommonContentGlobalSearchData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CommonContentGlobalSearchResponses,
    CommonContentGlobalSearchErrors,
    ThrowOnError
  >({url: "/api/commoncontent/search", ...options});

/**
 * List all inventory items aggregated by catalog item.
 *
 * Returns one row per distinct CatalogItem with a total Count summed across all three item kinds
 * (Standard, Unit, AssembledBundle). Supports filtering by warehouse, storage place, node,
 * catalog item type, and archive state.
 */
export const inventoryItemsGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<InventoryItemsGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    InventoryItemsGetAllResponses,
    InventoryItemsGetAllErrors,
    ThrowOnError
  >({url: "/api/inventory-items", ...options});

/**
 * List all unit inventory items (individual serialized items).
 */
export const inventoryItemsGetAllUnits = <ThrowOnError extends boolean = false>(
  options?: Options<InventoryItemsGetAllUnitsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    InventoryItemsGetAllUnitsResponses,
    InventoryItemsGetAllUnitsErrors,
    ThrowOnError
  >({url: "/api/inventory-items/units", ...options});

/**
 * List all assembled bundle inventory items (individual bundle instances).
 */
export const inventoryItemsGetAllAssembledBundles = <ThrowOnError extends boolean = false>(
  options?: Options<InventoryItemsGetAllAssembledBundlesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    InventoryItemsGetAllAssembledBundlesResponses,
    InventoryItemsGetAllAssembledBundlesErrors,
    ThrowOnError
  >({url: "/api/inventory-items/assembled-bundles", ...options});

/**
 * Get all available static permissions defined in the system.
 */
export const permissionsGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<PermissionsGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    PermissionsGetAllResponses,
    PermissionsGetAllErrors,
    ThrowOnError
  >({url: "/api/permissions", ...options});

/**
 * List receipts with pagination, filtering, and search.
 */
export const receiptsGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<ReceiptsGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ReceiptsGetAllResponses, ReceiptsGetAllErrors, ThrowOnError>({
    url: "/api/receipts",
    ...options,
  });

/**
 * Create a new receipt in Draft status.
 */
export const receiptsCreate = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<ReceiptsCreateResponses, ReceiptsCreateErrors, ThrowOnError>({
    url: "/api/receipts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a receipt. Only allowed in Draft status.
 */
export const receiptsDelete = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<ReceiptsDeleteResponses, ReceiptsDeleteErrors, ThrowOnError>({
    url: "/api/receipts/{id}",
    ...options,
  });

/**
 * Get full receipt details including items and placements.
 */
export const receiptsGetById = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsGetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<ReceiptsGetByIdResponses, ReceiptsGetByIdErrors, ThrowOnError>({
    url: "/api/receipts/{id}",
    ...options,
  });

/**
 * Update receipt name, reason, notes. Only allowed in Draft status.
 */
export const receiptsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).patch<ReceiptsUpdateResponses, ReceiptsUpdateErrors, ThrowOnError>({
    url: "/api/receipts/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Replace the full list of expected items. Allowed in Draft and Planned statuses.
 */
export const receiptsSyncItems = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsSyncItemsData, ThrowOnError>,
) =>
  (options.client ?? client).put<ReceiptsSyncItemsResponses, ReceiptsSyncItemsErrors, ThrowOnError>(
    {
      url: "/api/receipts/{id}/items",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    },
  );

/**
 * Update the actually received count for a specific item. Only in Processing status.
 */
export const receiptsUpdateReceivedCount = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsUpdateReceivedCountData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    ReceiptsUpdateReceivedCountResponses,
    ReceiptsUpdateReceivedCountErrors,
    ThrowOnError
  >({
    url: "/api/receipts/{id}/items/{itemId}/received-count",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Place Standard (count-based) items at a storage node. Only in Processing status.
 */
export const receiptsAddStandardPlacement = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsAddStandardPlacementData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ReceiptsAddStandardPlacementResponses,
    ReceiptsAddStandardPlacementErrors,
    ThrowOnError
  >({
    url: "/api/receipts/{id}/items/{itemId}/placements/standard",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Place a Unit (serialised) item at a storage node. Only in Processing status.
 */
export const receiptsAddUnitPlacement = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsAddUnitPlacementData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ReceiptsAddUnitPlacementResponses,
    ReceiptsAddUnitPlacementErrors,
    ThrowOnError
  >({
    url: "/api/receipts/{id}/items/{itemId}/placements/unit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Place an AssembledBundle item at a storage node. Only in Processing status.
 */
export const receiptsAddAssembledBundlePlacement = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsAddAssembledBundlePlacementData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ReceiptsAddAssembledBundlePlacementResponses,
    ReceiptsAddAssembledBundlePlacementErrors,
    ThrowOnError
  >({
    url: "/api/receipts/{id}/items/{itemId}/placements/assembled-bundle",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove a placement, reversing the inventory change. Only in Processing status.
 */
export const receiptsDeletePlacement = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsDeletePlacementData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ReceiptsDeletePlacementResponses,
    ReceiptsDeletePlacementErrors,
    ThrowOnError
  >({url: "/api/receipts/{id}/items/{itemId}/placements/{placementId}", ...options});

/**
 * Transition: Draft → Planned.
 */
export const receiptsPlan = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsPlanData, ThrowOnError>,
) =>
  (options.client ?? client).post<ReceiptsPlanResponses, ReceiptsPlanErrors, ThrowOnError>({
    url: "/api/receipts/{id}/plan",
    ...options,
  });

/**
 * Transition: Planned → Processing.
 */
export const receiptsStartProcessing = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsStartProcessingData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ReceiptsStartProcessingResponses,
    ReceiptsStartProcessingErrors,
    ThrowOnError
  >({url: "/api/receipts/{id}/start-processing", ...options});

/**
 * Transition: Processing → Finished. Validates that each item with a received count has enough placements.
 */
export const receiptsFinish = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsFinishData, ThrowOnError>,
) =>
  (options.client ?? client).post<ReceiptsFinishResponses, ReceiptsFinishErrors, ThrowOnError>({
    url: "/api/receipts/{id}/finish",
    ...options,
  });

/**
 * Revert one step back (Planned → Draft, Processing → Planned if no placements).
 */
export const receiptsRevert = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsRevertData, ThrowOnError>,
) =>
  (options.client ?? client).post<ReceiptsRevertResponses, ReceiptsRevertErrors, ThrowOnError>({
    url: "/api/receipts/{id}/revert",
    ...options,
  });

/**
 * Cancel the receipt. Allowed from Draft, Planned, and Processing (if no placements).
 */
export const receiptsCancel = <ThrowOnError extends boolean = false>(
  options: Options<ReceiptsCancelData, ThrowOnError>,
) =>
  (options.client ?? client).post<ReceiptsCancelResponses, ReceiptsCancelErrors, ThrowOnError>({
    url: "/api/receipts/{id}/cancel",
    ...options,
  });

/**
 * List all roles with their permissions.
 */
export const rolesGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<RolesGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RolesGetAllResponses, RolesGetAllErrors, ThrowOnError>({
    url: "/api/roles",
    ...options,
  });

/**
 * Atomically replace the entire roles collection.
 */
export const rolesUpdateAll = <ThrowOnError extends boolean = false>(
  options: Options<RolesUpdateAllData, ThrowOnError>,
) =>
  (options.client ?? client).put<RolesUpdateAllResponses, RolesUpdateAllErrors, ThrowOnError>({
    url: "/api/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search roles by name (id + name only, max 10 results).
 */
export const rolesSearch = <ThrowOnError extends boolean = false>(
  options?: Options<RolesSearchData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RolesSearchResponses, RolesSearchErrors, ThrowOnError>({
    url: "/api/roles/search",
    ...options,
  });

/**
 * Get a role by ID.
 */
export const rolesGetById = <ThrowOnError extends boolean = false>(
  options: Options<RolesGetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<RolesGetByIdResponses, RolesGetByIdErrors, ThrowOnError>({
    url: "/api/roles/{id}",
    ...options,
  });

/**
 * Get a flat list of all nodes for a storage place.
 *
 * Returns `StoragePlaceNodeDto[]` ordered by order then name — id, name, parentNodeId (null = root), order.
 */
export const storagePlacesGetNodes = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesGetNodesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    StoragePlacesGetNodesResponses,
    StoragePlacesGetNodesErrors,
    ThrowOnError
  >({url: "/api/storagePlaces/{id}/nodes", ...options});

/**
 * Add a node to a storage place.
 *
 * Body: `CreateStoragePlaceNodeRequest` — name (required), parentNodeId (optional, null = root node).
 * Returns the updated flat list.
 * Returns 422 `storagePlaceNodeNotFound` (field: `parentNodeId`) if the parent does not belong to this storage place.
 */
export const storagePlacesAddNode = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesAddNodeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StoragePlacesAddNodeResponses,
    StoragePlacesAddNodeErrors,
    ThrowOnError
  >({
    url: "/api/storagePlaces/{id}/nodes",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a node. Fails if the node has children — delete them first.
 *
 * Returns the updated flat list on success.
 */
export const storagePlacesDeleteNode = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesDeleteNodeData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    StoragePlacesDeleteNodeResponses,
    StoragePlacesDeleteNodeErrors,
    ThrowOnError
  >({url: "/api/storagePlaces/{id}/nodes/{nodeId}", ...options});

/**
 * Get a node by ID.
 */
export const storagePlacesGetNodeDetails = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesGetNodeDetailsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    StoragePlacesGetNodeDetailsResponses,
    StoragePlacesGetNodeDetailsErrors,
    ThrowOnError
  >({url: "/api/storagePlaces/{id}/nodes/{nodeId}", ...options});

/**
 * Update a node's name or parent.
 *
 * Body: `UpdateStoragePlaceNodeRequest` — name (required), parentNodeId (nullable, null = root node).
 * Returns the updated flat list.
 * Returns 422 `storagePlaceNodeCyclicParent` (field: `parentNodeId`) if the new parent is a descendant of this node or the node itself.
 */
export const storagePlacesUpdateNode = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesUpdateNodeData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    StoragePlacesUpdateNodeResponses,
    StoragePlacesUpdateNodeErrors,
    ThrowOnError
  >({
    url: "/api/storagePlaces/{id}/nodes/{nodeId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Bulk-update Order for a set of nodes.
 *
 * Body: `NodeOrderItem[]` — nodeId + order pairs.
 * Only the nodes included in the list are updated; others are unchanged.
 * Returns 422 `storagePlaceNodeNotFound` if any nodeId does not belong to this storage place.
 */
export const storagePlacesReorderNodes = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesReorderNodesData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    StoragePlacesReorderNodesResponses,
    StoragePlacesReorderNodesErrors,
    ThrowOnError
  >({
    url: "/api/storagePlaces/{id}/nodes/reorder",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all users (paginated).
 */
export const usersGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<UsersGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<UsersGetAllResponses, UsersGetAllErrors, ThrowOnError>({
    url: "/api/users",
    ...options,
  });

/**
 * Create a new user.
 */
export const usersCreate = <ThrowOnError extends boolean = false>(
  options: Options<UsersCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<UsersCreateResponses, UsersCreateErrors, ThrowOnError>({
    url: "/api/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a user.
 */
export const usersDelete = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<UsersDeleteResponses, UsersDeleteErrors, ThrowOnError>({
    url: "/api/users/{id}",
    ...options,
  });

/**
 * Get a user by ID.
 */
export const usersGetById = <ThrowOnError extends boolean = false>(
  options: Options<UsersGetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<UsersGetByIdResponses, UsersGetByIdErrors, ThrowOnError>({
    url: "/api/users/{id}",
    ...options,
  });

/**
 * Update a user's profile, roles, and direct permissions atomically.
 */
export const usersUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UsersUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<UsersUpdateResponses, UsersUpdateErrors, ThrowOnError>({
    url: "/api/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset another user's password (admin action, no current password required).
 */
export const usersChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<UsersChangePasswordData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UsersChangePasswordResponses,
    UsersChangePasswordErrors,
    ThrowOnError
  >({
    url: "/api/users/{id}/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all warehouses (paginated, optionally filtered by name).
 *
 * Query params: `page` (default 1), `pageSize` (default 20, max 200), `searchString` (optional).
 * Returns `Paginated&lt;WarehouseSummaryDto&gt;` — id, name, width, height, storagePlaceCount.
 * Requires `warehouses.view` (all warehouses) or `warehouses.view_assigned` (assigned warehouses only).
 */
export const warehousesGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<WarehousesGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<WarehousesGetAllResponses, WarehousesGetAllErrors, ThrowOnError>({
    url: "/api/warehouses",
    ...options,
  });

/**
 * Create a new warehouse with optional storage places.
 *
 * Body: `CreateWarehouseRequest` — name (required), width, height, storagePlaces (optional).
 */
export const warehousesCreate = <ThrowOnError extends boolean = false>(
  options: Options<WarehousesCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<WarehousesCreateResponses, WarehousesCreateErrors, ThrowOnError>({
    url: "/api/warehouses",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a warehouse and all its storage places.
 *
 * Returns 409 `warehouseHasItems` if the warehouse contains any stored items.
 * Requires `warehouses.edit` or `warehouses.edit_assigned` (assigned warehouses only).
 */
export const warehousesDelete = <ThrowOnError extends boolean = false>(
  options: Options<WarehousesDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    WarehousesDeleteResponses,
    WarehousesDeleteErrors,
    ThrowOnError
  >({url: "/api/warehouses/{id}", ...options});

/**
 * Get a warehouse by ID including its storage places.
 */
export const warehousesGetById = <ThrowOnError extends boolean = false>(
  options: Options<WarehousesGetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<WarehousesGetByIdResponses, WarehousesGetByIdErrors, ThrowOnError>(
    {url: "/api/warehouses/{id}", ...options},
  );

/**
 * Update a warehouse and atomically sync its storage places.
 *
 *     Body: `UpdateWarehouseRequest`. Storage place sync rules:
 * * id: null — create new storage place
 * * id present — update existing storage place
 * * existing storage place not in the list — delete
 * Returns 422 `storagePlaceNotFound` if any provided ID does not belong to this warehouse.
 * Requires `warehouses.edit` or `warehouses.edit_assigned` (assigned warehouses only).
 */
export const warehousesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<WarehousesUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<WarehousesUpdateResponses, WarehousesUpdateErrors, ThrowOnError>({
    url: "/api/warehouses/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all storage place nodes for a warehouse mapped to id + full path name for printing.
 */
export const warehousesGetByIdForPrint = <ThrowOnError extends boolean = false>(
  options: Options<WarehousesGetByIdForPrintData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    WarehousesGetByIdForPrintResponses,
    WarehousesGetByIdForPrintErrors,
    ThrowOnError
  >({url: "/api/warehouses/{id}/print", ...options});
