// This file is auto-generated by @hey-api/openapi-ts

import type {Client, Options as Options2, TDataShape} from "./client";
import {client} from "./client.gen";
import type {
  AuthChangeOwnPasswordData,
  AuthChangeOwnPasswordErrors,
  AuthChangeOwnPasswordResponses,
  AuthLoginData,
  AuthLoginErrors,
  AuthLoginResponses,
  AuthLogoutData,
  AuthLogoutErrors,
  AuthLogoutResponses,
  AuthMeData,
  AuthMeErrors,
  AuthMeResponses,
  AuthRefreshData,
  AuthRefreshErrors,
  AuthRefreshResponses,
  CatalogCreateData,
  CatalogCreateErrors,
  CatalogCreateResponses,
  CatalogDeleteData,
  CatalogDeleteErrors,
  CatalogDeleteResponses,
  CatalogGetAllData,
  CatalogGetAllErrors,
  CatalogGetAllResponses,
  CatalogGetByIdData,
  CatalogGetByIdErrors,
  CatalogGetByIdResponses,
  CatalogUpdateData,
  CatalogUpdateErrors,
  CatalogUpdateResponses,
  ChangelogGetAllData,
  ChangelogGetAllErrors,
  ChangelogGetAllResponses,
  HomePageContentGetHomePageContentData,
  HomePageContentGetHomePageContentErrors,
  HomePageContentGetHomePageContentResponses,
  PermissionsGetAllData,
  PermissionsGetAllErrors,
  PermissionsGetAllResponses,
  RolesGetAllData,
  RolesGetAllErrors,
  RolesGetAllResponses,
  RolesGetByIdData,
  RolesGetByIdErrors,
  RolesGetByIdResponses,
  RolesSearchData,
  RolesSearchErrors,
  RolesSearchResponses,
  RolesUpdateAllData,
  RolesUpdateAllErrors,
  RolesUpdateAllResponses,
  StoragePlacesAddNodeData,
  StoragePlacesAddNodeErrors,
  StoragePlacesAddNodeResponses,
  StoragePlacesDeleteNodeData,
  StoragePlacesDeleteNodeErrors,
  StoragePlacesDeleteNodeResponses,
  StoragePlacesGetNodeDetailsData,
  StoragePlacesGetNodeDetailsErrors,
  StoragePlacesGetNodeDetailsResponses,
  StoragePlacesGetNodesData,
  StoragePlacesGetNodesErrors,
  StoragePlacesGetNodesResponses,
  StoragePlacesUpdateNodeData,
  StoragePlacesUpdateNodeErrors,
  StoragePlacesUpdateNodeItemsData,
  StoragePlacesUpdateNodeItemsErrors,
  StoragePlacesUpdateNodeItemsResponses,
  StoragePlacesUpdateNodeResponses,
  UsersChangePasswordData,
  UsersChangePasswordErrors,
  UsersChangePasswordResponses,
  UsersCreateData,
  UsersCreateErrors,
  UsersCreateResponses,
  UsersDeleteData,
  UsersDeleteErrors,
  UsersDeleteResponses,
  UsersGetAllData,
  UsersGetAllErrors,
  UsersGetAllResponses,
  UsersGetByIdData,
  UsersGetByIdErrors,
  UsersGetByIdResponses,
  UsersUpdateData,
  UsersUpdateErrors,
  UsersUpdateResponses,
  WarehousesCreateData,
  WarehousesCreateErrors,
  WarehousesCreateResponses,
  WarehousesDeleteData,
  WarehousesDeleteErrors,
  WarehousesDeleteResponses,
  WarehousesGetAllData,
  WarehousesGetAllErrors,
  WarehousesGetAllResponses,
  WarehousesGetByIdData,
  WarehousesGetByIdErrors,
  WarehousesGetByIdForPrintData,
  WarehousesGetByIdForPrintErrors,
  WarehousesGetByIdForPrintResponses,
  WarehousesGetByIdResponses,
  WarehousesUpdateData,
  WarehousesUpdateErrors,
  WarehousesUpdateResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Authenticate with username and password.
 */
export const authLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh an access token using a valid refresh token.
 */
export const authRefresh = <ThrowOnError extends boolean = false>(
  options: Options<AuthRefreshData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError>({
    url: "/api/auth/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Revoke the current refresh token (logout).
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options: Options<AuthLogoutData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError>({
    url: "/api/auth/logout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Change the current user's own password (requires current password).
 */
export const authChangeOwnPassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthChangeOwnPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    AuthChangeOwnPasswordResponses,
    AuthChangeOwnPasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get the currently authenticated user's info, roles and permissions.
 */
export const authMe = <ThrowOnError extends boolean = false>(
  options?: Options<AuthMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AuthMeResponses, AuthMeErrors, ThrowOnError>({
    url: "/api/auth/me",
    ...options,
  });

/**
 * List all catalog items (paginated, optionally filtered by name).
 */
export const catalogGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<CatalogGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<CatalogGetAllResponses, CatalogGetAllErrors, ThrowOnError>({
    url: "/api/catalog",
    ...options,
  });

/**
 * Create a new catalog item with optional characteristics.
 */
export const catalogCreate = <ThrowOnError extends boolean = false>(
  options: Options<CatalogCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<CatalogCreateResponses, CatalogCreateErrors, ThrowOnError>({
    url: "/api/catalog",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a catalog item and all its characteristics.
 */
export const catalogDelete = <ThrowOnError extends boolean = false>(
  options: Options<CatalogDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<CatalogDeleteResponses, CatalogDeleteErrors, ThrowOnError>({
    url: "/api/catalog/{id}",
    ...options,
  });

/**
 * Get a catalog item by ID including its characteristics.
 */
export const catalogGetById = <ThrowOnError extends boolean = false>(
  options: Options<CatalogGetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<CatalogGetByIdResponses, CatalogGetByIdErrors, ThrowOnError>({
    url: "/api/catalog/{id}",
    ...options,
  });

/**
 * Update a catalog item and atomically sync its characteristics.
 *
 *     Characteristic sync rules:
 * * id: null — create new characteristic
 * * id present — update existing characteristic
 * * existing characteristic not in the list — delete
 * Returns 422 `catalogItemCharacteristicNotFound` if any provided ID does not belong to this item.
 */
export const catalogUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CatalogUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<CatalogUpdateResponses, CatalogUpdateErrors, ThrowOnError>({
    url: "/api/catalog/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List changelog entries (paginated).
 *
 * Query params: `page` (default 1), `pageSize` (default 20, max 200),
 * `entityType` (optional), `changeLogEntryType` (optional).
 * Returns `Paginated&lt;ChangeLogEntryDto&gt;` ordered by `createdAt` descending.
 */
export const changelogGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<ChangelogGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ChangelogGetAllResponses, ChangelogGetAllErrors, ThrowOnError>({
    url: "/api/changelog",
    ...options,
  });

/**
 * Get list of AppEntities for home page.
 */
export const homePageContentGetHomePageContent = <ThrowOnError extends boolean = false>(
  options?: Options<HomePageContentGetHomePageContentData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HomePageContentGetHomePageContentResponses,
    HomePageContentGetHomePageContentErrors,
    ThrowOnError
  >({url: "/api/homepagecontent", ...options});

/**
 * Get all available static permissions defined in the system.
 */
export const permissionsGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<PermissionsGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    PermissionsGetAllResponses,
    PermissionsGetAllErrors,
    ThrowOnError
  >({url: "/api/permissions", ...options});

/**
 * List all roles with their permissions.
 */
export const rolesGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<RolesGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RolesGetAllResponses, RolesGetAllErrors, ThrowOnError>({
    url: "/api/roles",
    ...options,
  });

/**
 * Atomically replace the entire roles collection.
 */
export const rolesUpdateAll = <ThrowOnError extends boolean = false>(
  options: Options<RolesUpdateAllData, ThrowOnError>,
) =>
  (options.client ?? client).put<RolesUpdateAllResponses, RolesUpdateAllErrors, ThrowOnError>({
    url: "/api/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search roles by name (id + name only, max 10 results).
 */
export const rolesSearch = <ThrowOnError extends boolean = false>(
  options?: Options<RolesSearchData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RolesSearchResponses, RolesSearchErrors, ThrowOnError>({
    url: "/api/roles/search",
    ...options,
  });

/**
 * Get a role by ID.
 */
export const rolesGetById = <ThrowOnError extends boolean = false>(
  options: Options<RolesGetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<RolesGetByIdResponses, RolesGetByIdErrors, ThrowOnError>({
    url: "/api/roles/{id}",
    ...options,
  });

/**
 * Get a flat list of all nodes for a storage place.
 *
 * Returns `StoragePlaceNodeDto[]` ordered by name — id, name, parentNodeId (null = root).
 */
export const storagePlacesGetNodes = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesGetNodesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    StoragePlacesGetNodesResponses,
    StoragePlacesGetNodesErrors,
    ThrowOnError
  >({url: "/api/storagePlaces/{id}/nodes", ...options});

/**
 * Add a node to a storage place.
 *
 * Body: `CreateStoragePlaceNodeRequest` — name (required), parentNodeId (optional, null = root node).
 * Returns the updated flat list.
 * Returns 422 `storagePlaceNodeNotFound` (field: `parentNodeId`) if the parent does not belong to this storage place.
 */
export const storagePlacesAddNode = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesAddNodeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StoragePlacesAddNodeResponses,
    StoragePlacesAddNodeErrors,
    ThrowOnError
  >({
    url: "/api/storagePlaces/{id}/nodes",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a node. Fails if the node has children — delete them first.
 *
 * Returns the updated flat list on success.
 */
export const storagePlacesDeleteNode = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesDeleteNodeData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    StoragePlacesDeleteNodeResponses,
    StoragePlacesDeleteNodeErrors,
    ThrowOnError
  >({url: "/api/storagePlaces/{id}/nodes/{nodeId}", ...options});

/**
 * Get a node by ID including its item groups.
 */
export const storagePlacesGetNodeDetails = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesGetNodeDetailsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    StoragePlacesGetNodeDetailsResponses,
    StoragePlacesGetNodeDetailsErrors,
    ThrowOnError
  >({url: "/api/storagePlaces/{id}/nodes/{nodeId}", ...options});

/**
 * Update a node's name or parent.
 *
 * Body: `UpdateStoragePlaceNodeRequest` — name (required), parentNodeId (nullable, null = root node).
 * Returns the updated flat list.
 * Returns 422 `storagePlaceNodeCyclicParent` (field: `parentNodeId`) if the new parent is a descendant of this node or the node itself.
 */
export const storagePlacesUpdateNode = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesUpdateNodeData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    StoragePlacesUpdateNodeResponses,
    StoragePlacesUpdateNodeErrors,
    ThrowOnError
  >({
    url: "/api/storagePlaces/{id}/nodes/{nodeId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Atomically sync item groups for a node.
 *
 *     Sync rules:
 * * id: null — create new item group
 * * id present — update existing item group
 * * existing item group not in the list — delete
 * Returns 422 `storagePlaceNodeItemsGroupNotFound` if any provided ID does not belong to this node.
 * Returns 422 `catalogItemCharacteristicNotFound` if any `catalogItemWithCharacteristicId` does not exist.
 */
export const storagePlacesUpdateNodeItems = <ThrowOnError extends boolean = false>(
  options: Options<StoragePlacesUpdateNodeItemsData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    StoragePlacesUpdateNodeItemsResponses,
    StoragePlacesUpdateNodeItemsErrors,
    ThrowOnError
  >({
    url: "/api/storagePlaces/{id}/nodes/{nodeId}/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all users (paginated).
 */
export const usersGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<UsersGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<UsersGetAllResponses, UsersGetAllErrors, ThrowOnError>({
    url: "/api/users",
    ...options,
  });

/**
 * Create a new user.
 */
export const usersCreate = <ThrowOnError extends boolean = false>(
  options: Options<UsersCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<UsersCreateResponses, UsersCreateErrors, ThrowOnError>({
    url: "/api/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a user.
 */
export const usersDelete = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<UsersDeleteResponses, UsersDeleteErrors, ThrowOnError>({
    url: "/api/users/{id}",
    ...options,
  });

/**
 * Get a user by ID.
 */
export const usersGetById = <ThrowOnError extends boolean = false>(
  options: Options<UsersGetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<UsersGetByIdResponses, UsersGetByIdErrors, ThrowOnError>({
    url: "/api/users/{id}",
    ...options,
  });

/**
 * Update a user's profile, roles, and direct permissions atomically.
 */
export const usersUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UsersUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<UsersUpdateResponses, UsersUpdateErrors, ThrowOnError>({
    url: "/api/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset another user's password (admin action, no current password required).
 */
export const usersChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<UsersChangePasswordData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UsersChangePasswordResponses,
    UsersChangePasswordErrors,
    ThrowOnError
  >({
    url: "/api/users/{id}/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all warehouses (paginated, optionally filtered by name).
 *
 * Query params: `page` (default 1), `pageSize` (default 20, max 200), `searchString` (optional).
 * Returns `Paginated&lt;WarehouseSummaryDto&gt;` — id, name, width, height, storagePlaceCount.
 */
export const warehousesGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<WarehousesGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<WarehousesGetAllResponses, WarehousesGetAllErrors, ThrowOnError>({
    url: "/api/warehouses",
    ...options,
  });

/**
 * Create a new warehouse with optional storage places.
 *
 * Body: `CreateWarehouseRequest` — name (required), width, height, storagePlaces (optional).
 */
export const warehousesCreate = <ThrowOnError extends boolean = false>(
  options: Options<WarehousesCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<WarehousesCreateResponses, WarehousesCreateErrors, ThrowOnError>({
    url: "/api/warehouses",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a warehouse and all its storage places.
 */
export const warehousesDelete = <ThrowOnError extends boolean = false>(
  options: Options<WarehousesDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    WarehousesDeleteResponses,
    WarehousesDeleteErrors,
    ThrowOnError
  >({url: "/api/warehouses/{id}", ...options});

/**
 * Get a warehouse by ID including its storage places.
 */
export const warehousesGetById = <ThrowOnError extends boolean = false>(
  options: Options<WarehousesGetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<WarehousesGetByIdResponses, WarehousesGetByIdErrors, ThrowOnError>(
    {url: "/api/warehouses/{id}", ...options},
  );

/**
 * Update a warehouse and atomically sync its storage places.
 *
 *     Body: `UpdateWarehouseRequest`. Storage place sync rules:
 * * id: null — create new storage place
 * * id present — update existing storage place
 * * existing storage place not in the list — delete
 * Returns 422 `storagePlaceNotFound` if any provided ID does not belong to this warehouse.
 */
export const warehousesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<WarehousesUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<WarehousesUpdateResponses, WarehousesUpdateErrors, ThrowOnError>({
    url: "/api/warehouses/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get all storage place nodes for a warehouse mapped to id + full path name for printing.
 */
export const warehousesGetByIdForPrint = <ThrowOnError extends boolean = false>(
  options: Options<WarehousesGetByIdForPrintData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    WarehousesGetByIdForPrintResponses,
    WarehousesGetByIdForPrintErrors,
    ThrowOnError
  >({url: "/api/warehouses/{id}/print", ...options});
