// This file is auto-generated by @hey-api/openapi-ts

import type {Client, Options as Options2, TDataShape} from "./client";
import {client} from "./client.gen";
import type {
  AuthChangeOwnPasswordData,
  AuthChangeOwnPasswordErrors,
  AuthChangeOwnPasswordResponses,
  AuthLoginData,
  AuthLoginErrors,
  AuthLoginResponses,
  AuthLogoutData,
  AuthLogoutErrors,
  AuthLogoutResponses,
  AuthMeData,
  AuthMeErrors,
  AuthMeResponses,
  AuthRefreshData,
  AuthRefreshErrors,
  AuthRefreshResponses,
  PermissionsGetAllData,
  PermissionsGetAllErrors,
  PermissionsGetAllResponses,
  RolesGetAllData,
  RolesGetAllErrors,
  RolesGetAllResponses,
  RolesSearchData,
  RolesSearchErrors,
  RolesSearchResponses,
  RolesUpdateAllData,
  RolesUpdateAllErrors,
  RolesUpdateAllResponses,
  UsersChangePasswordData,
  UsersChangePasswordErrors,
  UsersChangePasswordResponses,
  UsersCreateData,
  UsersCreateErrors,
  UsersCreateResponses,
  UsersDeleteData,
  UsersDeleteErrors,
  UsersDeleteResponses,
  UsersGetAllData,
  UsersGetAllErrors,
  UsersGetAllResponses,
  UsersGetByIdData,
  UsersGetByIdErrors,
  UsersGetByIdResponses,
  UsersUpdateData,
  UsersUpdateErrors,
  UsersUpdateResponses,
  WeatherForecastGetData,
  WeatherForecastGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Authenticate with username and password.
 */
export const authLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh an access token using a valid refresh token.
 */
export const authRefresh = <ThrowOnError extends boolean = false>(
  options: Options<AuthRefreshData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthRefreshResponses, AuthRefreshErrors, ThrowOnError>({
    url: "/api/auth/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Revoke the current refresh token (logout).
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options: Options<AuthLogoutData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError>({
    url: "/api/auth/logout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Change the current user's own password (requires current password).
 */
export const authChangeOwnPassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthChangeOwnPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    AuthChangeOwnPasswordResponses,
    AuthChangeOwnPasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get the currently authenticated user's info, roles and permissions.
 */
export const authMe = <ThrowOnError extends boolean = false>(
  options?: Options<AuthMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AuthMeResponses, AuthMeErrors, ThrowOnError>({
    url: "/api/auth/me",
    ...options,
  });

/**
 * Get all available static permissions defined in the system.
 */
export const permissionsGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<PermissionsGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    PermissionsGetAllResponses,
    PermissionsGetAllErrors,
    ThrowOnError
  >({url: "/api/permissions", ...options});

/**
 * List all roles with their permissions.
 */
export const rolesGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<RolesGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RolesGetAllResponses, RolesGetAllErrors, ThrowOnError>({
    url: "/api/roles",
    ...options,
  });

/**
 * Atomically replace the entire roles collection.
 */
export const rolesUpdateAll = <ThrowOnError extends boolean = false>(
  options: Options<RolesUpdateAllData, ThrowOnError>,
) =>
  (options.client ?? client).put<RolesUpdateAllResponses, RolesUpdateAllErrors, ThrowOnError>({
    url: "/api/roles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search roles by name (id + name only, max 10 results).
 */
export const rolesSearch = <ThrowOnError extends boolean = false>(
  options?: Options<RolesSearchData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RolesSearchResponses, RolesSearchErrors, ThrowOnError>({
    url: "/api/roles/search",
    ...options,
  });

/**
 * List all users (paginated).
 */
export const usersGetAll = <ThrowOnError extends boolean = false>(
  options?: Options<UsersGetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<UsersGetAllResponses, UsersGetAllErrors, ThrowOnError>({
    url: "/api/users",
    ...options,
  });

/**
 * Create a new user.
 */
export const usersCreate = <ThrowOnError extends boolean = false>(
  options: Options<UsersCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<UsersCreateResponses, UsersCreateErrors, ThrowOnError>({
    url: "/api/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a user.
 */
export const usersDelete = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).delete<UsersDeleteResponses, UsersDeleteErrors, ThrowOnError>({
    url: "/api/users/{id}",
    ...options,
  });

/**
 * Get a user by ID.
 */
export const usersGetById = <ThrowOnError extends boolean = false>(
  options: Options<UsersGetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<UsersGetByIdResponses, UsersGetByIdErrors, ThrowOnError>({
    url: "/api/users/{id}",
    ...options,
  });

/**
 * Update a user's profile, roles, and direct permissions atomically.
 */
export const usersUpdate = <ThrowOnError extends boolean = false>(
  options: Options<UsersUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<UsersUpdateResponses, UsersUpdateErrors, ThrowOnError>({
    url: "/api/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset another user's password (admin action, no current password required).
 */
export const usersChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<UsersChangePasswordData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UsersChangePasswordResponses,
    UsersChangePasswordErrors,
    ThrowOnError
  >({
    url: "/api/users/{id}/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const weatherForecastGet = <ThrowOnError extends boolean = false>(
  options?: Options<WeatherForecastGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<WeatherForecastGetResponses, unknown, ThrowOnError>({
    url: "/WeatherForecast",
    ...options,
  });
