// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://localhost:7095/" | (string & {});
};

export type AppFieldError = {
  code: ErrorCode;
  detail: string;
  args?: null | {
    [key: string]: unknown;
  };
};

export type AppProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number;
  detail?: null | string;
  instance?: null | string;
  errors: {
    [key: string]: Array<AppFieldError>;
  };
};

export type AssignRolePermissionRequest = {
  permission: PermissionName;
};

export type ChangeOwnPasswordRequest = {
  currentPassword: string;
  newPassword: string;
};

export type ChangePasswordRequest = {
  newPassword: string;
};

export type CreateRoleRequest = {
  name: string;
};

export type CreateUserRequest = {
  username: string;
  password: string;
  email?: null | string;
  firstName?: null | string;
  lastName?: null | string;
};

export type ErrorCode =
  | "invalidCredentials"
  | "tokenOutdated"
  | "tokenInvalid"
  | "refreshTokenInvalid"
  | "refreshTokenExpired"
  | "refreshTokenRevoked"
  | "permissionDenied"
  | "roleProtected"
  | "userNotFound"
  | "roleNotFound"
  | "permissionNotFound"
  | "userAlreadyExists"
  | "roleAlreadyExists"
  | "permissionAlreadyAssigned"
  | "required"
  | "tooShort"
  | "tooLong"
  | "invalidFormat"
  | "outOfRange"
  | "invalidJson"
  | "validationError";

export type LoginRequest = {
  username: string;
  password: string;
};

export type MeResponse = {
  id: string;
  username: string;
  email?: null | string;
  firstName?: null | string;
  lastName?: null | string;
  roles: Array<string>;
  permissions: Array<string>;
};

export type PaginatedOfUserDetailDto = {
  items: Array<UserDetailDto>;
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export type PermissionName =
  | "users.view"
  | "users.create"
  | "users.edit_profile"
  | "users.delete"
  | "users.manage_roles"
  | "users.reset_password"
  | "roles.view"
  | "roles.create"
  | "roles.edit"
  | "roles.delete"
  | "roles.manage_permissions";

export type RefreshRequest = {
  refreshToken: string;
};

export type RoleDto = {
  id: string;
  name: string;
};

export type TokenResponse = {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
};

export type UpdateRoleRequest = {
  name: string;
};

export type UpdateUserRequest = {
  email?: null | string;
  firstName?: null | string;
  lastName?: null | string;
  roleIds: Array<string>;
  directPermissions: Array<string>;
};

export type UserDetailDto = {
  id: string;
  username: string;
  email?: null | string;
  firstName?: null | string;
  lastName?: null | string;
  roles: Array<RoleDto>;
  directPermissions: Array<string>;
};

export type WeatherForecast = {
  date: string;
  temperatureC: number;
  temperatureF: number;
  summary?: null | string;
};

export type AuthLoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type AuthLoginErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
  /**
   * OK
   */
  200: TokenResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRefreshData = {
  body: RefreshRequest;
  path?: never;
  query?: never;
  url: "/api/auth/refresh";
};

export type AuthRefreshErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type AuthRefreshError = AuthRefreshErrors[keyof AuthRefreshErrors];

export type AuthRefreshResponses = {
  /**
   * OK
   */
  200: TokenResponse;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthLogoutData = {
  body: RefreshRequest;
  path?: never;
  query?: never;
  url: "/api/auth/logout";
};

export type AuthLogoutErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type AuthLogoutError = AuthLogoutErrors[keyof AuthLogoutErrors];

export type AuthLogoutResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthChangeOwnPasswordData = {
  body: ChangeOwnPasswordRequest;
  path?: never;
  query?: never;
  url: "/api/auth/password";
};

export type AuthChangeOwnPasswordErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type AuthChangeOwnPasswordError =
  AuthChangeOwnPasswordErrors[keyof AuthChangeOwnPasswordErrors];

export type AuthChangeOwnPasswordResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthChangeOwnPasswordResponse =
  AuthChangeOwnPasswordResponses[keyof AuthChangeOwnPasswordResponses];

export type AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/me";
};

export type AuthMeErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type AuthMeError = AuthMeErrors[keyof AuthMeErrors];

export type AuthMeResponses = {
  /**
   * OK
   */
  200: MeResponse;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type PermissionsGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/permissions";
};

export type PermissionsGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type PermissionsGetAllError = PermissionsGetAllErrors[keyof PermissionsGetAllErrors];

export type PermissionsGetAllResponses = {
  /**
   * OK
   */
  200: Array<string>;
};

export type PermissionsGetAllResponse =
  PermissionsGetAllResponses[keyof PermissionsGetAllResponses];

export type RolesGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/roles";
};

export type RolesGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type RolesGetAllError = RolesGetAllErrors[keyof RolesGetAllErrors];

export type RolesGetAllResponses = {
  /**
   * OK
   */
  200: Array<RoleDto>;
};

export type RolesGetAllResponse = RolesGetAllResponses[keyof RolesGetAllResponses];

export type RolesCreateData = {
  body: CreateRoleRequest;
  path?: never;
  query?: never;
  url: "/api/roles";
};

export type RolesCreateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Conflict
   */
  409: AppProblemDetails;
};

export type RolesCreateError = RolesCreateErrors[keyof RolesCreateErrors];

export type RolesCreateResponses = {
  /**
   * Created
   */
  201: RoleDto;
};

export type RolesCreateResponse = RolesCreateResponses[keyof RolesCreateResponses];

export type RolesDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/roles/{id}";
};

export type RolesDeleteErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type RolesDeleteError = RolesDeleteErrors[keyof RolesDeleteErrors];

export type RolesDeleteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type RolesDeleteResponse = RolesDeleteResponses[keyof RolesDeleteResponses];

export type RolesGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/roles/{id}";
};

export type RolesGetByIdErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type RolesGetByIdError = RolesGetByIdErrors[keyof RolesGetByIdErrors];

export type RolesGetByIdResponses = {
  /**
   * OK
   */
  200: RoleDto;
};

export type RolesGetByIdResponse = RolesGetByIdResponses[keyof RolesGetByIdResponses];

export type RolesUpdateData = {
  body: UpdateRoleRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/roles/{id}";
};

export type RolesUpdateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type RolesUpdateError = RolesUpdateErrors[keyof RolesUpdateErrors];

export type RolesUpdateResponses = {
  /**
   * OK
   */
  200: RoleDto;
};

export type RolesUpdateResponse = RolesUpdateResponses[keyof RolesUpdateResponses];

export type RolesGetPermissionsData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/roles/{id}/permissions";
};

export type RolesGetPermissionsErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type RolesGetPermissionsError = RolesGetPermissionsErrors[keyof RolesGetPermissionsErrors];

export type RolesGetPermissionsResponses = {
  /**
   * OK
   */
  200: Array<string>;
};

export type RolesGetPermissionsResponse =
  RolesGetPermissionsResponses[keyof RolesGetPermissionsResponses];

export type RolesAddPermissionData = {
  body: AssignRolePermissionRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/roles/{id}/permissions";
};

export type RolesAddPermissionErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Conflict
   */
  409: AppProblemDetails;
};

export type RolesAddPermissionError = RolesAddPermissionErrors[keyof RolesAddPermissionErrors];

export type RolesAddPermissionResponses = {
  /**
   * No Content
   */
  204: void;
};

export type RolesAddPermissionResponse =
  RolesAddPermissionResponses[keyof RolesAddPermissionResponses];

export type RolesRemovePermissionData = {
  body?: never;
  path: {
    id: string;
    permission: string;
  };
  query?: never;
  url: "/api/roles/{id}/permissions/{permission}";
};

export type RolesRemovePermissionErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type RolesRemovePermissionError =
  RolesRemovePermissionErrors[keyof RolesRemovePermissionErrors];

export type RolesRemovePermissionResponses = {
  /**
   * No Content
   */
  204: void;
};

export type RolesRemovePermissionResponse =
  RolesRemovePermissionResponses[keyof RolesRemovePermissionResponses];

export type UsersGetAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    searchString?: string;
  };
  url: "/api/users";
};

export type UsersGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type UsersGetAllError = UsersGetAllErrors[keyof UsersGetAllErrors];

export type UsersGetAllResponses = {
  /**
   * OK
   */
  200: PaginatedOfUserDetailDto;
};

export type UsersGetAllResponse = UsersGetAllResponses[keyof UsersGetAllResponses];

export type UsersCreateData = {
  body: CreateUserRequest;
  path?: never;
  query?: never;
  url: "/api/users";
};

export type UsersCreateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Conflict
   */
  409: AppProblemDetails;
};

export type UsersCreateError = UsersCreateErrors[keyof UsersCreateErrors];

export type UsersCreateResponses = {
  /**
   * Created
   */
  201: UserDetailDto;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UsersDeleteErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type UsersDeleteError = UsersDeleteErrors[keyof UsersDeleteErrors];

export type UsersDeleteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type UsersDeleteResponse = UsersDeleteResponses[keyof UsersDeleteResponses];

export type UsersGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UsersGetByIdErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type UsersGetByIdError = UsersGetByIdErrors[keyof UsersGetByIdErrors];

export type UsersGetByIdResponses = {
  /**
   * OK
   */
  200: UserDetailDto;
};

export type UsersGetByIdResponse = UsersGetByIdResponses[keyof UsersGetByIdResponses];

export type UsersUpdateData = {
  body: UpdateUserRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UsersUpdateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type UsersUpdateError = UsersUpdateErrors[keyof UsersUpdateErrors];

export type UsersUpdateResponses = {
  /**
   * OK
   */
  200: UserDetailDto;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersChangePasswordData = {
  body: ChangePasswordRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}/password";
};

export type UsersChangePasswordErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type UsersChangePasswordError = UsersChangePasswordErrors[keyof UsersChangePasswordErrors];

export type UsersChangePasswordResponses = {
  /**
   * No Content
   */
  204: void;
};

export type UsersChangePasswordResponse =
  UsersChangePasswordResponses[keyof UsersChangePasswordResponses];

export type WeatherForecastGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/WeatherForecast";
};

export type WeatherForecastGetResponses = {
  /**
   * OK
   */
  200: Array<WeatherForecast>;
};

export type WeatherForecastGetResponse =
  WeatherForecastGetResponses[keyof WeatherForecastGetResponses];
