// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://localhost:7095/" | (string & {});
};

export type AppEntity = {
  id?: null | string;
  name?: null | string;
  type: AppEntityType;
  additionalFields?: null | {
    [key: string]: unknown;
  };
};

export type AppEntityType =
  | "unknown"
  | "user"
  | "roles"
  | "warehouse"
  | "catalogItem"
  | "storagePlaceNode"
  | "receipt"
  | "writeoff";

export type AppFieldError = {
  code: ErrorCode;
  detail: string;
  args?: null | {
    [key: string]: unknown;
  };
};

export type AppProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number;
  detail?: null | string;
  instance?: null | string;
  errors: {
    [key: string]: Array<AppFieldError>;
  };
};

export type AssembledBundleInventoryItemDto = {
  id: string;
  catalogItem: CatalogItemSummaryDto;
  warehouseId: string;
  warehouseName: string;
  storagePlaceId: string;
  storagePlaceName: string;
  nodeId: string;
  nodeName: string;
};

export type AssembledBundleInventoryItemSortBy = "warehouseName" | "storagePlaceName" | "nodeName";

export type AssembledBundlePlacementComponentRequest = {
  /**
   * The catalog item ID of this component.
   */
  catalogItemId: string;
  /**
   * Quantity to place. Required for Standard/Bundle components.
   * Null when a unit item is supplied via Guid? AssembledBundlePlacementComponentRequest.UnitInventoryItemId or CreateUnitItemRequest? AssembledBundlePlacementComponentRequest.NewUnitItem.
   */
  quantity?: null | number;
  /**
   * Existing `UnitInventoryItem` to include as a component. Mutually exclusive with CreateUnitItemRequest? AssembledBundlePlacementComponentRequest.NewUnitItem.
   */
  unitInventoryItemId?: null | string;
  newUnitItem?: null | CreateUnitItemRequest;
};

export type BatchStandardPlacementItemRequest = {
  itemId: string;
  count: number;
};

export type BatchStandardPlacementRequest = {
  storagePlaceNodeId: string;
  items: Array<BatchStandardPlacementItemRequest>;
};

export type BundleComponentDto = {
  id: string;
  componentId: string;
  componentName: string;
  componentType: CatalogItemType;
  quantity: number;
};

export type BundleComponentRequest = {
  id?: null | string;
  componentId: string;
  quantity: number;
};

export type CatalogItemDto = {
  id: string;
  type: CatalogItemType;
  name: string;
  fullName: string;
  article: string;
  barcode?: null | string;
  description?: null | string;
  notes?: null | string;
  isArchived: boolean;
  groupId?: null | string;
  groupName?: null | string;
  sourceBundleId?: null | string;
  tags: Array<CatalogItemTagDto>;
  components: Array<BundleComponentDto>;
  variationIds: Array<string>;
  memberIds: Array<string>;
  children: Array<CatalogItemDto>;
};

export type CatalogItemSelectDto = {
  id: string;
  type: CatalogItemType;
  name: string;
  fullName: string;
  article: string;
  isArchived: boolean;
};

export type CatalogItemSummaryDto = {
  id: string;
  type: CatalogItemType;
  name: string;
  fullName: string;
  article: string;
  barcode?: null | string;
  isArchived: boolean;
  tags: Array<CatalogItemTagDto>;
};

export type CatalogItemTagDto = {
  id: string;
  name: string;
};

export type CatalogItemType =
  | "standard"
  | "unit"
  | "productGroup"
  | "variation"
  | "bundle"
  | "assembledBundle";

export type CatalogSortBy = "name" | "article" | "barcode" | "type";

export type ChangeLogDiff = {
  path: string;
  from?: unknown;
  to?: unknown;
};

export type ChangeLogEntryDto = {
  id: string;
  entityType: AppEntityType;
  entityId: string;
  changeLogEntryType: ChangeLogEntryType;
  diffs: Array<ChangeLogDiff>;
  userName?: null | string;
  userId?: null | string;
  createdAt: string;
  context?: null | JsonElement;
  action?: null | string;
  actionData?: null | JsonElement;
};

export type ChangeLogEntryType = "added" | "modified" | "deleted";

export type ChangeOwnPasswordRequest = {
  currentPassword: string;
  newPassword: string;
};

export type ChangePasswordRequest = {
  newPassword: string;
};

export type CreateAssembledBundlePlacementRequest = {
  storagePlaceNodeId: string;
  components: Array<AssembledBundlePlacementComponentRequest>;
};

export type CreateCatalogItemRequest = {
  type: CatalogItemType;
  name: string;
  article: string;
  barcode?: null | string;
};

export type CreateCatalogItemTagRequest = {
  name: string;
};

export type CreateReceiptRequest = {
  name: string;
  reason: ReceiptReason;
  warehouseId: string;
  notes?: null | string;
  plannedDeliveryDate?: null | string;
};

export type CreateStandardPlacementRequest = {
  storagePlaceNodeId: string;
  count: number;
};

export type CreateStoragePlaceNodeRequest = {
  name: string;
  parentNodeId?: null | string;
  order: number;
};

/**
 * Data required to create a new unit (serialised) inventory item.
 */
export type CreateUnitItemRequest = {
  inventoryNumber: string;
};

export type CreateUnitPlacementRequest = {
  storagePlaceNodeId: string;
  unitItem: CreateUnitItemRequest;
};

export type CreateUserRequest = {
  username: string;
  password: string;
  email?: null | string;
  firstName?: null | string;
  lastName?: null | string;
};

export type CreateWarehouseRequest = {
  name: string;
  width: number;
  height: number;
  storagePlaces: Array<StoragePlaceItem>;
  layoutObjects: Array<WarehouseLayoutElementItem>;
};

export type CreateWriteoffRequest = {
  name: string;
  reason: WriteoffReason;
  warehouseId: string;
  notes?: null | string;
};

export type ErrorCode =
  | "invalidCredentials"
  | "tokenOutdated"
  | "tokenInvalid"
  | "refreshTokenInvalid"
  | "refreshTokenExpired"
  | "refreshTokenRevoked"
  | "permissionDenied"
  | "roleProtected"
  | "userNotFound"
  | "roleNotFound"
  | "permissionNotFound"
  | "userAlreadyExists"
  | "roleAlreadyExists"
  | "permissionAlreadyAssigned"
  | "warehouseNotFound"
  | "storagePlaceNotFound"
  | "catalogItemNotFound"
  | "catalogItemCharacteristicNotFound"
  | "storagePlaceNodeNotFound"
  | "storagePlaceNodeHasChildren"
  | "storagePlaceNodeHasItems"
  | "storagePlaceNodeParentHasItems"
  | "storagePlaceNodeCyclicParent"
  | "storagePlaceNodeItemsGroupNotFound"
  | "catalogItemCharacteristicDuplicate"
  | "warehouseHasItems"
  | "storagePlaceHasItems"
  | "catalogItemIsInUse"
  | "catalogItemIsImmutable"
  | "catalogItemArticleDuplicate"
  | "catalogItemBarcodeDuplicate"
  | "catalogItemCharacteristicBarcodeDuplicate"
  | "catalogItemGroupInvalid"
  | "catalogItemManagedByGroup"
  | "catalogItemVariationInvalid"
  | "catalogItemComponentInvalid"
  | "catalogItemComponentNotFound"
  | "catalogItemCircularDependency"
  | "catalogItemTooManyCombinations"
  | "unitInventoryItemNotFound"
  | "assembledBundleItemNotFound"
  | "inventoryItemMovedToAnotherNodeAfterPlacementCreated"
  | "transferSameNode"
  | "writeoffNotFound"
  | "writeoffNotDraft"
  | "writeoffHasNoItems"
  | "writeoffItemNotFound"
  | "writeoffInsufficientInventory"
  | "writeoffNotAssignedToWarehouse"
  | "receiptNotFound"
  | "receiptInvalidStatusTransition"
  | "receiptHasPlacements"
  | "receiptItemNotFound"
  | "receiptItemPlacementNotFound"
  | "receiptNotAssignedToWarehouse"
  | "receiptItemsUnderplaced"
  | "receiptItemsOverplaced"
  | "insufficientInventory"
  | "unitInventoryItemNumberDuplicate"
  | "routeNotFound"
  | "required"
  | "tooShort"
  | "tooLong"
  | "invalidFormat"
  | "outOfRange"
  | "invalidJson"
  | "passwordTooShort"
  | "passwordAtLeastOneDigit"
  | "passwordAtLeastOneUppercase"
  | "passwordAtLeastOneLowercase"
  | "passwordInvalid"
  | "validationError";

export type EventDto = {
  appEntity: AppEntity;
  startDate: string;
  endDate: string;
};

export type ExecuteTransferRequest = {
  fromNodeId: string;
  toNodeId: string;
  items: Array<TransferItemRequest>;
};

export type InventoryItemSortBy = "name" | "fullName" | "article" | "type" | "count";

export type InventoryItemSummaryDto = {
  catalogItemId: string;
  catalogItem: CatalogItemSummaryDto;
  count: number;
};

export type ItemsGroupDto = {
  id: string;
  count: number;
  catalogItem: NodeCatalogItemDto;
};

export type JsonElement = unknown;

export type LoginRequest = {
  username: string;
  password: string;
};

export type MeResponse = {
  id: string;
  username: string;
  email?: null | string;
  firstName?: null | string;
  lastName?: null | string;
  roles: Array<string>;
  permissions: Array<string>;
};

export type NodeCatalogItemDto = {
  id: string;
  name: string;
  article: string;
  barcode?: null | string;
};

export type NodeOrderItem = {
  nodeId: string;
  order: number;
};

export type PaginatedOfAssembledBundleInventoryItemDto = {
  items: Array<AssembledBundleInventoryItemDto>;
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export type PaginatedOfCatalogItemSummaryDto = {
  items: Array<CatalogItemSummaryDto>;
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export type PaginatedOfChangeLogEntryDto = {
  items: Array<ChangeLogEntryDto>;
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export type PaginatedOfInventoryItemSummaryDto = {
  items: Array<InventoryItemSummaryDto>;
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export type PaginatedOfReceiptSummaryDto = {
  items: Array<ReceiptSummaryDto>;
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export type PaginatedOfUnitInventoryItemDto = {
  items: Array<UnitInventoryItemDto>;
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export type PaginatedOfUserDetailDto = {
  items: Array<UserDetailDto>;
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export type PaginatedOfWarehouseSummaryDto = {
  items: Array<WarehouseSummaryDto>;
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export type PaginatedOfWriteoffSummaryDto = {
  items: Array<WriteoffSummaryDto>;
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
};

export type PermissionName =
  | "users.view"
  | "users.create"
  | "users.edit_profile"
  | "users.delete"
  | "users.manage_roles_and_permissions"
  | "users.manage_assigned_warehouses"
  | "users.reset_password"
  | "roles.view"
  | "roles.edit"
  | "warehouses.view"
  | "warehouses.edit"
  | "warehouses.view_assigned"
  | "warehouses.edit_assigned"
  | "catalog.view"
  | "catalog.edit"
  | "changelog.view"
  | "transfers.execute"
  | "transfers.execute_assigned"
  | "writeoffs.view"
  | "writeoffs.edit"
  | "writeoffs.view_assigned"
  | "writeoffs.edit_assigned"
  | "receipts.view"
  | "receipts.edit"
  | "receipts.view_assigned"
  | "receipts.edit_assigned"
  | "receipts.process_assigned";

export type ProductGroupChildRequest = {
  id?: null | string;
  type: CatalogItemType;
  name: string;
  article: string;
  barcode?: null | string;
  description?: null | string;
  notes?: null | string;
  isArchived: boolean;
  tags: Array<string>;
};

export type QuickAddReceiptItemRequest = {
  catalogItemId: string;
};

export type ReceiptDto = {
  id: string;
  number: number;
  name: string;
  reason: ReceiptReason;
  status: ReceiptStatus;
  notes?: null | string;
  plannedDeliveryDate?: null | string;
  createdAt: string;
  warehouseId: string;
  warehouseName: string;
  totalPlannedCount: number;
  totalReceivedCount: number;
  items: Array<ReceiptItemDto>;
};

export type ReceiptItemDto = {
  id: string;
  catalogItemId: string;
  catalogItem: CatalogItemSummaryDto;
  plannedCount: number;
  receivedCount?: null | number;
  notes?: null | string;
  placements: Array<ReceiptItemPlacementDto>;
};

export type ReceiptItemPlacementDto = {
  id: string;
  storagePlaceNodeId: string;
  /**
   * Full breadcrumb path from root to node: [StoragePlace, …parents…, Node].
   */
  nodePath: Array<string>;
  /**
   * Quantity placed. Positive for Standard items; zero for Unit/AssembledBundle placements.
   */
  count: number;
  /**
   * Set for Unit item placements.
   */
  unitInventoryItemId?: null | string;
  inventoryNumber?: null | string;
  /**
   * Set for AssembledBundle item placements.
   */
  assembledBundleInventoryItemId?: null | string;
};

export type ReceiptItemRequest = {
  catalogItemId: string;
  plannedCount: number;
  notes?: null | string;
};

export type ReceiptReason = "newGoods" | "return" | "other";

export type ReceiptSortBy =
  | "name"
  | "number"
  | "status"
  | "createdAt"
  | "warehouseName"
  | "plannedDeliveryDate";

export type ReceiptStatus = "draft" | "planned" | "processing" | "finished" | "canceled";

export type ReceiptSummaryDto = {
  id: string;
  number: number;
  name: string;
  reason: ReceiptReason;
  status: ReceiptStatus;
  warehouseId: string;
  warehouseName: string;
  itemsCount: number;
  totalPlannedCount: number;
  totalReceivedCount: number;
  createdAt: string;
  plannedDeliveryDate?: null | string;
};

export type RefreshRequest = {
  refreshToken: string;
};

export type RoleDto = {
  id: string;
  name: string;
};

export type RoleWithPermissionsDto = {
  id: string;
  name: string;
  order: number;
  permissions: Array<string>;
};

export type SortOrder = "asc" | "desc";

export type StoragePlaceDto = {
  id: string;
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  totalItemsCount: number;
};

export type StoragePlaceItem = {
  id?: null | string;
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
};

export type StoragePlaceNodeDetailsDto = {
  id: string;
  name: Array<string>;
  storagePlaceId: string;
  parentNodeId?: null | string;
  order: number;
  /**
   * Current standard items stored in this node. Used for inventory changelog diffing.
   */
  itemsGroups: Array<ItemsGroupDto>;
  /**
   * Count of unit inventory items at this node. Used for inventory changelog diffing.
   */
  unitItemsCount: number;
  /**
   * Count of assembled bundle inventory items at this node. Used for inventory changelog diffing.
   */
  assembledBundlesCount: number;
};

export type StoragePlaceNodeDto = {
  id: string;
  name: string;
  parentNodeId?: null | string;
  order: number;
  totalItemsCount: number;
};

export type StoragePlaceNodePrintDto = {
  id: string;
  name: Array<string>;
};

export type TokenResponse = {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
};

export type TransferItemRequest = {
  /**
   * Filled for Standard (count-based) items. Requires int? TransferItemRequest.Count.
   */
  catalogItemId?: null | string;
  /**
   * Required when Guid? TransferItemRequest.CatalogItemId is set.
   */
  count?: null | number;
  /**
   * Filled for Unit items.
   */
  unitItemId?: null | string;
  /**
   * Filled for AssembledBundle items.
   */
  assembledBundleItemId?: null | string;
};

export type UnitInventoryItemDto = {
  id: string;
  inventoryNumber: string;
  catalogItem: CatalogItemSummaryDto;
  warehouseId: string;
  warehouseName: string;
  storagePlaceId: string;
  storagePlaceName: string;
  nodeId: string;
  nodeName: string;
};

export type UnitInventoryItemSortBy =
  | "inventoryNumber"
  | "warehouseName"
  | "storagePlaceName"
  | "nodeName";

export type UpdateCatalogItemRequest = {
  name: string;
  article: string;
  barcode?: null | string;
  description?: null | string;
  notes?: null | string;
  isArchived: boolean;
  tags: Array<string>;
  groupId?: null | string;
  memberIds: Array<string>;
  components: Array<BundleComponentRequest>;
  children: Array<ProductGroupChildRequest>;
};

export type UpdateReceiptRequest = {
  name: string;
  reason: ReceiptReason;
  notes?: null | string;
  plannedDeliveryDate?: null | string;
};

export type UpdateReceivedCountRequest = {
  receivedCount?: null | number;
};

export type UpdateRoleItem = {
  id?: null | string;
  name: string;
  order: number;
  permissions: Array<string>;
};

export type UpdateStoragePlaceNodeRequest = {
  name: string;
  parentNodeId?: null | string;
  order: number;
};

export type UpdateUserRequest = {
  email?: null | string;
  firstName?: null | string;
  lastName?: null | string;
  roleIds: Array<string>;
  directPermissions: Array<string>;
  assignedWarehouseIds: Array<string>;
};

export type UpdateWarehouseRequest = {
  name: string;
  width: number;
  height: number;
  defaultStoragePlaceNodeId?: null | string;
  storagePlaces: Array<StoragePlaceItem>;
  layoutObjects: Array<WarehouseLayoutElementItem>;
};

export type UpdateWriteoffRequest = {
  name: string;
  reason: WriteoffReason;
  notes?: null | string;
};

export type UserDetailDto = {
  id: string;
  username: string;
  email?: null | string;
  firstName?: null | string;
  lastName?: null | string;
  roles: Array<RoleDto>;
  directPermissions: Array<string>;
  assignedWarehouses: Array<WarehouseSummaryDto>;
};

export type WarehouseDto = {
  id: string;
  name: string;
  width: number;
  height: number;
  defaultStoragePlaceNodeId?: null | string;
  storagePlaces: Array<StoragePlaceDto>;
  layoutObjects: Array<WarehouseLayoutElementDto>;
  totalItemsCount: number;
};

export type WarehouseLayoutElementDto = {
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  type: WarehouseLayoutObjectType;
};

export type WarehouseLayoutElementItem = {
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  type: WarehouseLayoutObjectType;
};

export type WarehouseLayoutObjectType = "wall" | "passage";

export type WarehouseSummaryDto = {
  id: string;
  name: string;
  width: number;
  height: number;
  storagePlaceCount: number;
  totalItemsCount: number;
};

export type WriteoffDto = {
  id: string;
  number: number;
  name: string;
  reason: WriteoffReason;
  status: WriteoffStatus;
  notes?: null | string;
  createdAt: string;
  warehouseId: string;
  warehouseName: string;
  items: Array<WriteoffItemDto>;
};

export type WriteoffItemDto = {
  id: string;
  sourceNodeId: string;
  sourceNodePath: Array<string>;
  notes?: null | string;
  catalogItemId?: null | string;
  catalogItem?: null | CatalogItemSummaryDto;
  count: number;
  unitInventoryItemId?: null | string;
  inventoryNumber?: null | string;
  assembledBundleInventoryItemId?: null | string;
  /**
   * Catalog item display name. Populated for all item types.
   */
  catalogItemName: string;
};

export type WriteoffItemRequest = {
  sourceNodeId: string;
  catalogItemId?: null | string;
  count?: null | number;
  unitInventoryItemId?: null | string;
  assembledBundleInventoryItemId?: null | string;
  notes?: null | string;
};

export type WriteoffReason = "loss" | "defect" | "other";

export type WriteoffSortBy = "number" | "name" | "status" | "createdAt" | "warehouseName";

export type WriteoffStatus = "draft" | "finished" | "canceled";

export type WriteoffSummaryDto = {
  id: string;
  number: number;
  name: string;
  reason: WriteoffReason;
  status: WriteoffStatus;
  warehouseId: string;
  warehouseName: string;
  itemsCount: number;
  createdAt: string;
};

export type AuthLoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type AuthLoginErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
  /**
   * OK
   */
  200: TokenResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthRefreshData = {
  body: RefreshRequest;
  path?: never;
  query?: never;
  url: "/api/auth/refresh";
};

export type AuthRefreshErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type AuthRefreshError = AuthRefreshErrors[keyof AuthRefreshErrors];

export type AuthRefreshResponses = {
  /**
   * OK
   */
  200: TokenResponse;
};

export type AuthRefreshResponse = AuthRefreshResponses[keyof AuthRefreshResponses];

export type AuthLogoutData = {
  body: RefreshRequest;
  path?: never;
  query?: never;
  url: "/api/auth/logout";
};

export type AuthLogoutErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type AuthLogoutError = AuthLogoutErrors[keyof AuthLogoutErrors];

export type AuthLogoutResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthChangeOwnPasswordData = {
  body: ChangeOwnPasswordRequest;
  path?: never;
  query?: never;
  url: "/api/auth/password";
};

export type AuthChangeOwnPasswordErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type AuthChangeOwnPasswordError =
  AuthChangeOwnPasswordErrors[keyof AuthChangeOwnPasswordErrors];

export type AuthChangeOwnPasswordResponses = {
  /**
   * No Content
   */
  204: void;
};

export type AuthChangeOwnPasswordResponse =
  AuthChangeOwnPasswordResponses[keyof AuthChangeOwnPasswordResponses];

export type AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/me";
};

export type AuthMeErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type AuthMeError = AuthMeErrors[keyof AuthMeErrors];

export type AuthMeResponses = {
  /**
   * OK
   */
  200: MeResponse;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type CatalogGetTagsData = {
  body?: never;
  path?: never;
  query?: {
    search?: string;
  };
  url: "/api/catalog/tags";
};

export type CatalogGetTagsErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type CatalogGetTagsError = CatalogGetTagsErrors[keyof CatalogGetTagsErrors];

export type CatalogGetTagsResponses = {
  /**
   * OK
   */
  200: Array<CatalogItemTagDto>;
};

export type CatalogGetTagsResponse = CatalogGetTagsResponses[keyof CatalogGetTagsResponses];

export type CatalogCreateTagData = {
  body: CreateCatalogItemTagRequest;
  path?: never;
  query?: never;
  url: "/api/catalog/tags";
};

export type CatalogCreateTagErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type CatalogCreateTagError = CatalogCreateTagErrors[keyof CatalogCreateTagErrors];

export type CatalogCreateTagResponses = {
  /**
   * Created
   */
  201: CatalogItemTagDto;
};

export type CatalogCreateTagResponse = CatalogCreateTagResponses[keyof CatalogCreateTagResponses];

export type CatalogGetAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    searchString?: string;
    sortBy?: CatalogSortBy;
    sortOrder?: SortOrder;
    itemTypes?: Array<CatalogItemType>;
    isArchived?: boolean;
  };
  url: "/api/catalog";
};

export type CatalogGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type CatalogGetAllError = CatalogGetAllErrors[keyof CatalogGetAllErrors];

export type CatalogGetAllResponses = {
  /**
   * OK
   */
  200: PaginatedOfCatalogItemSummaryDto;
};

export type CatalogGetAllResponse = CatalogGetAllResponses[keyof CatalogGetAllResponses];

export type CatalogCreateData = {
  body: CreateCatalogItemRequest;
  path?: never;
  query?: never;
  url: "/api/catalog";
};

export type CatalogCreateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type CatalogCreateError = CatalogCreateErrors[keyof CatalogCreateErrors];

export type CatalogCreateResponses = {
  /**
   * Created
   */
  201: CatalogItemDto;
};

export type CatalogCreateResponse = CatalogCreateResponses[keyof CatalogCreateResponses];

export type CatalogGetForSelectData = {
  body?: never;
  path?: never;
  query?: {
    searchString?: string;
    types?: Array<CatalogItemType>;
  };
  url: "/api/catalog/for-select";
};

export type CatalogGetForSelectErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type CatalogGetForSelectError = CatalogGetForSelectErrors[keyof CatalogGetForSelectErrors];

export type CatalogGetForSelectResponses = {
  /**
   * OK
   */
  200: Array<CatalogItemSelectDto>;
};

export type CatalogGetForSelectResponse =
  CatalogGetForSelectResponses[keyof CatalogGetForSelectResponses];

export type CatalogDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/catalog/{id}";
};

export type CatalogDeleteErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Conflict
   */
  409: AppProblemDetails;
};

export type CatalogDeleteError = CatalogDeleteErrors[keyof CatalogDeleteErrors];

export type CatalogDeleteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type CatalogDeleteResponse = CatalogDeleteResponses[keyof CatalogDeleteResponses];

export type CatalogGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/catalog/{id}";
};

export type CatalogGetByIdErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type CatalogGetByIdError = CatalogGetByIdErrors[keyof CatalogGetByIdErrors];

export type CatalogGetByIdResponses = {
  /**
   * OK
   */
  200: CatalogItemDto;
};

export type CatalogGetByIdResponse = CatalogGetByIdResponses[keyof CatalogGetByIdResponses];

export type CatalogUpdateData = {
  body: UpdateCatalogItemRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/catalog/{id}";
};

export type CatalogUpdateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type CatalogUpdateError = CatalogUpdateErrors[keyof CatalogUpdateErrors];

export type CatalogUpdateResponses = {
  /**
   * OK
   */
  200: CatalogItemDto;
};

export type CatalogUpdateResponse = CatalogUpdateResponses[keyof CatalogUpdateResponses];

export type ChangelogGetAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    entityType?: AppEntityType;
    changeLogEntryType?: ChangeLogEntryType;
  };
  url: "/api/changelog";
};

export type ChangelogGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type ChangelogGetAllError = ChangelogGetAllErrors[keyof ChangelogGetAllErrors];

export type ChangelogGetAllResponses = {
  /**
   * OK
   */
  200: PaginatedOfChangeLogEntryDto;
};

export type ChangelogGetAllResponse = ChangelogGetAllResponses[keyof ChangelogGetAllResponses];

export type CommonContentGetHomePageContentData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/commoncontent";
};

export type CommonContentGetHomePageContentErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type CommonContentGetHomePageContentError =
  CommonContentGetHomePageContentErrors[keyof CommonContentGetHomePageContentErrors];

export type CommonContentGetHomePageContentResponses = {
  /**
   * OK
   */
  200: Array<AppEntity>;
};

export type CommonContentGetHomePageContentResponse =
  CommonContentGetHomePageContentResponses[keyof CommonContentGetHomePageContentResponses];

export type CommonContentGlobalSearchData = {
  body?: never;
  path?: never;
  query?: {
    searchString?: string;
  };
  url: "/api/commoncontent/search";
};

export type CommonContentGlobalSearchErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type CommonContentGlobalSearchError =
  CommonContentGlobalSearchErrors[keyof CommonContentGlobalSearchErrors];

export type CommonContentGlobalSearchResponses = {
  /**
   * OK
   */
  200: Array<AppEntity>;
};

export type CommonContentGlobalSearchResponse =
  CommonContentGlobalSearchResponses[keyof CommonContentGlobalSearchResponses];

export type EventsGetEventsData = {
  body?: never;
  path?: never;
  query?: {
    startDate?: string;
    endDate?: string;
  };
  url: "/api/events";
};

export type EventsGetEventsErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type EventsGetEventsError = EventsGetEventsErrors[keyof EventsGetEventsErrors];

export type EventsGetEventsResponses = {
  /**
   * OK
   */
  200: Array<EventDto>;
};

export type EventsGetEventsResponse = EventsGetEventsResponses[keyof EventsGetEventsResponses];

export type InventoryItemsGetAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    searchString?: string;
    warehouseId?: string;
    storagePlaceId?: string;
    nodeId?: string;
    catalogItemType?: CatalogItemType;
    isArchived?: boolean;
    sortBy?: InventoryItemSortBy;
    sortOrder?: SortOrder;
  };
  url: "/api/inventory-items";
};

export type InventoryItemsGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type InventoryItemsGetAllError =
  InventoryItemsGetAllErrors[keyof InventoryItemsGetAllErrors];

export type InventoryItemsGetAllResponses = {
  /**
   * OK
   */
  200: PaginatedOfInventoryItemSummaryDto;
};

export type InventoryItemsGetAllResponse =
  InventoryItemsGetAllResponses[keyof InventoryItemsGetAllResponses];

export type InventoryItemsGetAllUnitsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    searchString?: string;
    warehouseId?: string;
    storagePlaceId?: string;
    nodeId?: string;
    catalogItemId?: string;
    sortBy?: UnitInventoryItemSortBy;
    sortOrder?: SortOrder;
  };
  url: "/api/inventory-items/units";
};

export type InventoryItemsGetAllUnitsErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type InventoryItemsGetAllUnitsError =
  InventoryItemsGetAllUnitsErrors[keyof InventoryItemsGetAllUnitsErrors];

export type InventoryItemsGetAllUnitsResponses = {
  /**
   * OK
   */
  200: PaginatedOfUnitInventoryItemDto;
};

export type InventoryItemsGetAllUnitsResponse =
  InventoryItemsGetAllUnitsResponses[keyof InventoryItemsGetAllUnitsResponses];

export type InventoryItemsGetAllAssembledBundlesData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    searchString?: string;
    warehouseId?: string;
    storagePlaceId?: string;
    nodeId?: string;
    catalogItemId?: string;
    sortBy?: AssembledBundleInventoryItemSortBy;
    sortOrder?: SortOrder;
  };
  url: "/api/inventory-items/assembled-bundles";
};

export type InventoryItemsGetAllAssembledBundlesErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type InventoryItemsGetAllAssembledBundlesError =
  InventoryItemsGetAllAssembledBundlesErrors[keyof InventoryItemsGetAllAssembledBundlesErrors];

export type InventoryItemsGetAllAssembledBundlesResponses = {
  /**
   * OK
   */
  200: PaginatedOfAssembledBundleInventoryItemDto;
};

export type InventoryItemsGetAllAssembledBundlesResponse =
  InventoryItemsGetAllAssembledBundlesResponses[keyof InventoryItemsGetAllAssembledBundlesResponses];

export type PermissionsGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/permissions";
};

export type PermissionsGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type PermissionsGetAllError = PermissionsGetAllErrors[keyof PermissionsGetAllErrors];

export type PermissionsGetAllResponses = {
  /**
   * OK
   */
  200: Array<string>;
};

export type PermissionsGetAllResponse =
  PermissionsGetAllResponses[keyof PermissionsGetAllResponses];

export type ReceiptsGetAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    searchString?: string;
    warehouseId?: string;
    status?: ReceiptStatus;
    reason?: ReceiptReason;
    sortBy?: ReceiptSortBy;
    sortOrder?: SortOrder;
  };
  url: "/api/receipts";
};

export type ReceiptsGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type ReceiptsGetAllError = ReceiptsGetAllErrors[keyof ReceiptsGetAllErrors];

export type ReceiptsGetAllResponses = {
  /**
   * OK
   */
  200: PaginatedOfReceiptSummaryDto;
};

export type ReceiptsGetAllResponse = ReceiptsGetAllResponses[keyof ReceiptsGetAllResponses];

export type ReceiptsCreateData = {
  body: CreateReceiptRequest;
  path?: never;
  query?: never;
  url: "/api/receipts";
};

export type ReceiptsCreateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsCreateError = ReceiptsCreateErrors[keyof ReceiptsCreateErrors];

export type ReceiptsCreateResponses = {
  /**
   * Created
   */
  201: ReceiptDto;
};

export type ReceiptsCreateResponse = ReceiptsCreateResponses[keyof ReceiptsCreateResponses];

export type ReceiptsDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}";
};

export type ReceiptsDeleteErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsDeleteError = ReceiptsDeleteErrors[keyof ReceiptsDeleteErrors];

export type ReceiptsDeleteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type ReceiptsDeleteResponse = ReceiptsDeleteResponses[keyof ReceiptsDeleteResponses];

export type ReceiptsGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}";
};

export type ReceiptsGetByIdErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type ReceiptsGetByIdError = ReceiptsGetByIdErrors[keyof ReceiptsGetByIdErrors];

export type ReceiptsGetByIdResponses = {
  /**
   * OK
   */
  200: ReceiptDto;
};

export type ReceiptsGetByIdResponse = ReceiptsGetByIdResponses[keyof ReceiptsGetByIdResponses];

export type ReceiptsUpdateData = {
  body: UpdateReceiptRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}";
};

export type ReceiptsUpdateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsUpdateError = ReceiptsUpdateErrors[keyof ReceiptsUpdateErrors];

export type ReceiptsUpdateResponses = {
  /**
   * OK
   */
  200: ReceiptDto;
};

export type ReceiptsUpdateResponse = ReceiptsUpdateResponses[keyof ReceiptsUpdateResponses];

export type ReceiptsQuickAddItemData = {
  body: QuickAddReceiptItemRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}/items/quick-add";
};

export type ReceiptsQuickAddItemErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsQuickAddItemError =
  ReceiptsQuickAddItemErrors[keyof ReceiptsQuickAddItemErrors];

export type ReceiptsQuickAddItemResponses = {
  /**
   * OK
   */
  200: ReceiptDto;
};

export type ReceiptsQuickAddItemResponse =
  ReceiptsQuickAddItemResponses[keyof ReceiptsQuickAddItemResponses];

export type ReceiptsSyncItemsData = {
  body: Array<ReceiptItemRequest>;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}/items";
};

export type ReceiptsSyncItemsErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsSyncItemsError = ReceiptsSyncItemsErrors[keyof ReceiptsSyncItemsErrors];

export type ReceiptsSyncItemsResponses = {
  /**
   * OK
   */
  200: ReceiptDto;
};

export type ReceiptsSyncItemsResponse =
  ReceiptsSyncItemsResponses[keyof ReceiptsSyncItemsResponses];

export type ReceiptsUpdateReceivedCountData = {
  body: UpdateReceivedCountRequest;
  path: {
    id: string;
    itemId: string;
  };
  query?: never;
  url: "/api/receipts/{id}/items/{itemId}/received-count";
};

export type ReceiptsUpdateReceivedCountErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsUpdateReceivedCountError =
  ReceiptsUpdateReceivedCountErrors[keyof ReceiptsUpdateReceivedCountErrors];

export type ReceiptsUpdateReceivedCountResponses = {
  /**
   * OK
   */
  200: ReceiptItemDto;
};

export type ReceiptsUpdateReceivedCountResponse =
  ReceiptsUpdateReceivedCountResponses[keyof ReceiptsUpdateReceivedCountResponses];

export type ReceiptsAddStandardPlacementData = {
  body: CreateStandardPlacementRequest;
  path: {
    id: string;
    itemId: string;
  };
  query?: never;
  url: "/api/receipts/{id}/items/{itemId}/placements/standard";
};

export type ReceiptsAddStandardPlacementErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsAddStandardPlacementError =
  ReceiptsAddStandardPlacementErrors[keyof ReceiptsAddStandardPlacementErrors];

export type ReceiptsAddStandardPlacementResponses = {
  /**
   * OK
   */
  200: ReceiptItemDto;
};

export type ReceiptsAddStandardPlacementResponse =
  ReceiptsAddStandardPlacementResponses[keyof ReceiptsAddStandardPlacementResponses];

export type ReceiptsAddStandardPlacementBatchData = {
  body: BatchStandardPlacementRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}/placements/standard/batch";
};

export type ReceiptsAddStandardPlacementBatchErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsAddStandardPlacementBatchError =
  ReceiptsAddStandardPlacementBatchErrors[keyof ReceiptsAddStandardPlacementBatchErrors];

export type ReceiptsAddStandardPlacementBatchResponses = {
  /**
   * OK
   */
  200: ReceiptDto;
};

export type ReceiptsAddStandardPlacementBatchResponse =
  ReceiptsAddStandardPlacementBatchResponses[keyof ReceiptsAddStandardPlacementBatchResponses];

export type ReceiptsAddUnitPlacementData = {
  body: CreateUnitPlacementRequest;
  path: {
    id: string;
    itemId: string;
  };
  query?: never;
  url: "/api/receipts/{id}/items/{itemId}/placements/unit";
};

export type ReceiptsAddUnitPlacementErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsAddUnitPlacementError =
  ReceiptsAddUnitPlacementErrors[keyof ReceiptsAddUnitPlacementErrors];

export type ReceiptsAddUnitPlacementResponses = {
  /**
   * OK
   */
  200: ReceiptItemDto;
};

export type ReceiptsAddUnitPlacementResponse =
  ReceiptsAddUnitPlacementResponses[keyof ReceiptsAddUnitPlacementResponses];

export type ReceiptsAddAssembledBundlePlacementData = {
  body: CreateAssembledBundlePlacementRequest;
  path: {
    id: string;
    itemId: string;
  };
  query?: never;
  url: "/api/receipts/{id}/items/{itemId}/placements/assembled-bundle";
};

export type ReceiptsAddAssembledBundlePlacementErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsAddAssembledBundlePlacementError =
  ReceiptsAddAssembledBundlePlacementErrors[keyof ReceiptsAddAssembledBundlePlacementErrors];

export type ReceiptsAddAssembledBundlePlacementResponses = {
  /**
   * OK
   */
  200: ReceiptItemDto;
};

export type ReceiptsAddAssembledBundlePlacementResponse =
  ReceiptsAddAssembledBundlePlacementResponses[keyof ReceiptsAddAssembledBundlePlacementResponses];

export type ReceiptsDeletePlacementData = {
  body?: never;
  path: {
    id: string;
    itemId: string;
    placementId: string;
  };
  query?: never;
  url: "/api/receipts/{id}/items/{itemId}/placements/{placementId}";
};

export type ReceiptsDeletePlacementErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsDeletePlacementError =
  ReceiptsDeletePlacementErrors[keyof ReceiptsDeletePlacementErrors];

export type ReceiptsDeletePlacementResponses = {
  /**
   * OK
   */
  200: ReceiptItemDto;
};

export type ReceiptsDeletePlacementResponse =
  ReceiptsDeletePlacementResponses[keyof ReceiptsDeletePlacementResponses];

export type ReceiptsPlanData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}/plan";
};

export type ReceiptsPlanErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsPlanError = ReceiptsPlanErrors[keyof ReceiptsPlanErrors];

export type ReceiptsPlanResponses = {
  /**
   * OK
   */
  200: ReceiptDto;
};

export type ReceiptsPlanResponse = ReceiptsPlanResponses[keyof ReceiptsPlanResponses];

export type ReceiptsStartProcessingData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}/start-processing";
};

export type ReceiptsStartProcessingErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsStartProcessingError =
  ReceiptsStartProcessingErrors[keyof ReceiptsStartProcessingErrors];

export type ReceiptsStartProcessingResponses = {
  /**
   * OK
   */
  200: ReceiptDto;
};

export type ReceiptsStartProcessingResponse =
  ReceiptsStartProcessingResponses[keyof ReceiptsStartProcessingResponses];

export type ReceiptsFinishData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}/finish";
};

export type ReceiptsFinishErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsFinishError = ReceiptsFinishErrors[keyof ReceiptsFinishErrors];

export type ReceiptsFinishResponses = {
  /**
   * OK
   */
  200: ReceiptDto;
};

export type ReceiptsFinishResponse = ReceiptsFinishResponses[keyof ReceiptsFinishResponses];

export type ReceiptsRevertData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}/revert";
};

export type ReceiptsRevertErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsRevertError = ReceiptsRevertErrors[keyof ReceiptsRevertErrors];

export type ReceiptsRevertResponses = {
  /**
   * OK
   */
  200: ReceiptDto;
};

export type ReceiptsRevertResponse = ReceiptsRevertResponses[keyof ReceiptsRevertResponses];

export type ReceiptsCancelData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/receipts/{id}/cancel";
};

export type ReceiptsCancelErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type ReceiptsCancelError = ReceiptsCancelErrors[keyof ReceiptsCancelErrors];

export type ReceiptsCancelResponses = {
  /**
   * OK
   */
  200: ReceiptDto;
};

export type ReceiptsCancelResponse = ReceiptsCancelResponses[keyof ReceiptsCancelResponses];

export type RolesGetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/roles";
};

export type RolesGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type RolesGetAllError = RolesGetAllErrors[keyof RolesGetAllErrors];

export type RolesGetAllResponses = {
  /**
   * OK
   */
  200: Array<RoleWithPermissionsDto>;
};

export type RolesGetAllResponse = RolesGetAllResponses[keyof RolesGetAllResponses];

export type RolesUpdateAllData = {
  body: Array<UpdateRoleItem>;
  path?: never;
  query?: never;
  url: "/api/roles";
};

export type RolesUpdateAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type RolesUpdateAllError = RolesUpdateAllErrors[keyof RolesUpdateAllErrors];

export type RolesUpdateAllResponses = {
  /**
   * OK
   */
  200: Array<RoleWithPermissionsDto>;
};

export type RolesUpdateAllResponse = RolesUpdateAllResponses[keyof RolesUpdateAllResponses];

export type RolesSearchData = {
  body?: never;
  path?: never;
  query?: {
    searchString?: string;
  };
  url: "/api/roles/search";
};

export type RolesSearchErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type RolesSearchError = RolesSearchErrors[keyof RolesSearchErrors];

export type RolesSearchResponses = {
  /**
   * OK
   */
  200: Array<RoleDto>;
};

export type RolesSearchResponse = RolesSearchResponses[keyof RolesSearchResponses];

export type RolesGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/roles/{id}";
};

export type RolesGetByIdErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type RolesGetByIdError = RolesGetByIdErrors[keyof RolesGetByIdErrors];

export type RolesGetByIdResponses = {
  /**
   * OK
   */
  200: RoleDto;
};

export type RolesGetByIdResponse = RolesGetByIdResponses[keyof RolesGetByIdResponses];

export type StoragePlacesGetNodesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/storagePlaces/{id}/nodes";
};

export type StoragePlacesGetNodesErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type StoragePlacesGetNodesError =
  StoragePlacesGetNodesErrors[keyof StoragePlacesGetNodesErrors];

export type StoragePlacesGetNodesResponses = {
  /**
   * OK
   */
  200: Array<StoragePlaceNodeDto>;
};

export type StoragePlacesGetNodesResponse =
  StoragePlacesGetNodesResponses[keyof StoragePlacesGetNodesResponses];

export type StoragePlacesAddNodeData = {
  body: CreateStoragePlaceNodeRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/storagePlaces/{id}/nodes";
};

export type StoragePlacesAddNodeErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type StoragePlacesAddNodeError =
  StoragePlacesAddNodeErrors[keyof StoragePlacesAddNodeErrors];

export type StoragePlacesAddNodeResponses = {
  /**
   * OK
   */
  200: Array<StoragePlaceNodeDto>;
};

export type StoragePlacesAddNodeResponse =
  StoragePlacesAddNodeResponses[keyof StoragePlacesAddNodeResponses];

export type StoragePlacesDeleteNodeData = {
  body?: never;
  path: {
    id: string;
    nodeId: string;
  };
  query?: never;
  url: "/api/storagePlaces/{id}/nodes/{nodeId}";
};

export type StoragePlacesDeleteNodeErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type StoragePlacesDeleteNodeError =
  StoragePlacesDeleteNodeErrors[keyof StoragePlacesDeleteNodeErrors];

export type StoragePlacesDeleteNodeResponses = {
  /**
   * OK
   */
  200: Array<StoragePlaceNodeDto>;
};

export type StoragePlacesDeleteNodeResponse =
  StoragePlacesDeleteNodeResponses[keyof StoragePlacesDeleteNodeResponses];

export type StoragePlacesGetNodeDetailsData = {
  body?: never;
  path: {
    id: string;
    nodeId: string;
  };
  query?: never;
  url: "/api/storagePlaces/{id}/nodes/{nodeId}";
};

export type StoragePlacesGetNodeDetailsErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type StoragePlacesGetNodeDetailsError =
  StoragePlacesGetNodeDetailsErrors[keyof StoragePlacesGetNodeDetailsErrors];

export type StoragePlacesGetNodeDetailsResponses = {
  /**
   * OK
   */
  200: StoragePlaceNodeDetailsDto;
};

export type StoragePlacesGetNodeDetailsResponse =
  StoragePlacesGetNodeDetailsResponses[keyof StoragePlacesGetNodeDetailsResponses];

export type StoragePlacesUpdateNodeData = {
  body: UpdateStoragePlaceNodeRequest;
  path: {
    id: string;
    nodeId: string;
  };
  query?: never;
  url: "/api/storagePlaces/{id}/nodes/{nodeId}";
};

export type StoragePlacesUpdateNodeErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type StoragePlacesUpdateNodeError =
  StoragePlacesUpdateNodeErrors[keyof StoragePlacesUpdateNodeErrors];

export type StoragePlacesUpdateNodeResponses = {
  /**
   * OK
   */
  200: Array<StoragePlaceNodeDto>;
};

export type StoragePlacesUpdateNodeResponse =
  StoragePlacesUpdateNodeResponses[keyof StoragePlacesUpdateNodeResponses];

export type StoragePlacesReorderNodesData = {
  body: Array<NodeOrderItem>;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/storagePlaces/{id}/nodes/reorder";
};

export type StoragePlacesReorderNodesErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type StoragePlacesReorderNodesError =
  StoragePlacesReorderNodesErrors[keyof StoragePlacesReorderNodesErrors];

export type StoragePlacesReorderNodesResponses = {
  /**
   * OK
   */
  200: Array<StoragePlaceNodeDto>;
};

export type StoragePlacesReorderNodesResponse =
  StoragePlacesReorderNodesResponses[keyof StoragePlacesReorderNodesResponses];

export type TransfersExecuteData = {
  body: ExecuteTransferRequest;
  path?: never;
  query?: never;
  url: "/api/transfers";
};

export type TransfersExecuteErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type TransfersExecuteError = TransfersExecuteErrors[keyof TransfersExecuteErrors];

export type TransfersExecuteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type TransfersExecuteResponse = TransfersExecuteResponses[keyof TransfersExecuteResponses];

export type UsersGetAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    searchString?: string;
    role?: string;
    warehouse?: string;
  };
  url: "/api/users";
};

export type UsersGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type UsersGetAllError = UsersGetAllErrors[keyof UsersGetAllErrors];

export type UsersGetAllResponses = {
  /**
   * OK
   */
  200: PaginatedOfUserDetailDto;
};

export type UsersGetAllResponse = UsersGetAllResponses[keyof UsersGetAllResponses];

export type UsersCreateData = {
  body: CreateUserRequest;
  path?: never;
  query?: never;
  url: "/api/users";
};

export type UsersCreateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Conflict
   */
  409: AppProblemDetails;
};

export type UsersCreateError = UsersCreateErrors[keyof UsersCreateErrors];

export type UsersCreateResponses = {
  /**
   * Created
   */
  201: UserDetailDto;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UsersDeleteErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type UsersDeleteError = UsersDeleteErrors[keyof UsersDeleteErrors];

export type UsersDeleteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type UsersDeleteResponse = UsersDeleteResponses[keyof UsersDeleteResponses];

export type UsersGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UsersGetByIdErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type UsersGetByIdError = UsersGetByIdErrors[keyof UsersGetByIdErrors];

export type UsersGetByIdResponses = {
  /**
   * OK
   */
  200: UserDetailDto;
};

export type UsersGetByIdResponse = UsersGetByIdResponses[keyof UsersGetByIdResponses];

export type UsersUpdateData = {
  body: UpdateUserRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type UsersUpdateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type UsersUpdateError = UsersUpdateErrors[keyof UsersUpdateErrors];

export type UsersUpdateResponses = {
  /**
   * OK
   */
  200: UserDetailDto;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type UsersChangePasswordData = {
  body: ChangePasswordRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/users/{id}/password";
};

export type UsersChangePasswordErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type UsersChangePasswordError = UsersChangePasswordErrors[keyof UsersChangePasswordErrors];

export type UsersChangePasswordResponses = {
  /**
   * No Content
   */
  204: void;
};

export type UsersChangePasswordResponse =
  UsersChangePasswordResponses[keyof UsersChangePasswordResponses];

export type WarehousesGetAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    searchString?: string;
  };
  url: "/api/warehouses";
};

export type WarehousesGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type WarehousesGetAllError = WarehousesGetAllErrors[keyof WarehousesGetAllErrors];

export type WarehousesGetAllResponses = {
  /**
   * OK
   */
  200: PaginatedOfWarehouseSummaryDto;
};

export type WarehousesGetAllResponse = WarehousesGetAllResponses[keyof WarehousesGetAllResponses];

export type WarehousesCreateData = {
  body: CreateWarehouseRequest;
  path?: never;
  query?: never;
  url: "/api/warehouses";
};

export type WarehousesCreateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type WarehousesCreateError = WarehousesCreateErrors[keyof WarehousesCreateErrors];

export type WarehousesCreateResponses = {
  /**
   * Created
   */
  201: WarehouseDto;
};

export type WarehousesCreateResponse = WarehousesCreateResponses[keyof WarehousesCreateResponses];

export type WarehousesDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/warehouses/{id}";
};

export type WarehousesDeleteErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Conflict
   */
  409: AppProblemDetails;
};

export type WarehousesDeleteError = WarehousesDeleteErrors[keyof WarehousesDeleteErrors];

export type WarehousesDeleteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type WarehousesDeleteResponse = WarehousesDeleteResponses[keyof WarehousesDeleteResponses];

export type WarehousesGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/warehouses/{id}";
};

export type WarehousesGetByIdErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type WarehousesGetByIdError = WarehousesGetByIdErrors[keyof WarehousesGetByIdErrors];

export type WarehousesGetByIdResponses = {
  /**
   * OK
   */
  200: WarehouseDto;
};

export type WarehousesGetByIdResponse =
  WarehousesGetByIdResponses[keyof WarehousesGetByIdResponses];

export type WarehousesUpdateData = {
  body: UpdateWarehouseRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/warehouses/{id}";
};

export type WarehousesUpdateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Conflict
   */
  409: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type WarehousesUpdateError = WarehousesUpdateErrors[keyof WarehousesUpdateErrors];

export type WarehousesUpdateResponses = {
  /**
   * OK
   */
  200: WarehouseDto;
};

export type WarehousesUpdateResponse = WarehousesUpdateResponses[keyof WarehousesUpdateResponses];

export type WarehousesGetByIdForPrintData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/warehouses/{id}/print";
};

export type WarehousesGetByIdForPrintErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type WarehousesGetByIdForPrintError =
  WarehousesGetByIdForPrintErrors[keyof WarehousesGetByIdForPrintErrors];

export type WarehousesGetByIdForPrintResponses = {
  /**
   * OK
   */
  200: Array<StoragePlaceNodePrintDto>;
};

export type WarehousesGetByIdForPrintResponse =
  WarehousesGetByIdForPrintResponses[keyof WarehousesGetByIdForPrintResponses];

export type WarehousesGetDefaultNodeData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/warehouses/{id}/default-node";
};

export type WarehousesGetDefaultNodeErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type WarehousesGetDefaultNodeError =
  WarehousesGetDefaultNodeErrors[keyof WarehousesGetDefaultNodeErrors];

export type WarehousesGetDefaultNodeResponses = {
  /**
   * OK
   */
  200: StoragePlaceNodeDetailsDto;
};

export type WarehousesGetDefaultNodeResponse =
  WarehousesGetDefaultNodeResponses[keyof WarehousesGetDefaultNodeResponses];

export type WriteoffsGetAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    searchString?: string;
    warehouseId?: string;
    status?: WriteoffStatus;
    reason?: WriteoffReason;
    sortBy?: WriteoffSortBy;
    sortOrder?: SortOrder;
  };
  url: "/api/writeoffs";
};

export type WriteoffsGetAllErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
};

export type WriteoffsGetAllError = WriteoffsGetAllErrors[keyof WriteoffsGetAllErrors];

export type WriteoffsGetAllResponses = {
  /**
   * OK
   */
  200: PaginatedOfWriteoffSummaryDto;
};

export type WriteoffsGetAllResponse = WriteoffsGetAllResponses[keyof WriteoffsGetAllResponses];

export type WriteoffsCreateData = {
  body: CreateWriteoffRequest;
  path?: never;
  query?: never;
  url: "/api/writeoffs";
};

export type WriteoffsCreateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type WriteoffsCreateError = WriteoffsCreateErrors[keyof WriteoffsCreateErrors];

export type WriteoffsCreateResponses = {
  /**
   * Created
   */
  201: WriteoffDto;
};

export type WriteoffsCreateResponse = WriteoffsCreateResponses[keyof WriteoffsCreateResponses];

export type WriteoffsDeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/writeoffs/{id}";
};

export type WriteoffsDeleteErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type WriteoffsDeleteError = WriteoffsDeleteErrors[keyof WriteoffsDeleteErrors];

export type WriteoffsDeleteResponses = {
  /**
   * No Content
   */
  204: void;
};

export type WriteoffsDeleteResponse = WriteoffsDeleteResponses[keyof WriteoffsDeleteResponses];

export type WriteoffsGetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/writeoffs/{id}";
};

export type WriteoffsGetByIdErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
};

export type WriteoffsGetByIdError = WriteoffsGetByIdErrors[keyof WriteoffsGetByIdErrors];

export type WriteoffsGetByIdResponses = {
  /**
   * OK
   */
  200: WriteoffDto;
};

export type WriteoffsGetByIdResponse = WriteoffsGetByIdResponses[keyof WriteoffsGetByIdResponses];

export type WriteoffsUpdateData = {
  body: UpdateWriteoffRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/writeoffs/{id}";
};

export type WriteoffsUpdateErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type WriteoffsUpdateError = WriteoffsUpdateErrors[keyof WriteoffsUpdateErrors];

export type WriteoffsUpdateResponses = {
  /**
   * OK
   */
  200: WriteoffDto;
};

export type WriteoffsUpdateResponse = WriteoffsUpdateResponses[keyof WriteoffsUpdateResponses];

export type WriteoffsSyncItemsData = {
  body: Array<WriteoffItemRequest>;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/writeoffs/{id}/items";
};

export type WriteoffsSyncItemsErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type WriteoffsSyncItemsError = WriteoffsSyncItemsErrors[keyof WriteoffsSyncItemsErrors];

export type WriteoffsSyncItemsResponses = {
  /**
   * OK
   */
  200: WriteoffDto;
};

export type WriteoffsSyncItemsResponse =
  WriteoffsSyncItemsResponses[keyof WriteoffsSyncItemsResponses];

export type WriteoffsFinishData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/writeoffs/{id}/finish";
};

export type WriteoffsFinishErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type WriteoffsFinishError = WriteoffsFinishErrors[keyof WriteoffsFinishErrors];

export type WriteoffsFinishResponses = {
  /**
   * OK
   */
  200: WriteoffDto;
};

export type WriteoffsFinishResponse = WriteoffsFinishResponses[keyof WriteoffsFinishResponses];

export type WriteoffsCancelData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/writeoffs/{id}/cancel";
};

export type WriteoffsCancelErrors = {
  /**
   * Unauthorized
   */
  401: AppProblemDetails;
  /**
   * Forbidden
   */
  403: AppProblemDetails;
  /**
   * Not Found
   */
  404: AppProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: AppProblemDetails;
};

export type WriteoffsCancelError = WriteoffsCancelErrors[keyof WriteoffsCancelErrors];

export type WriteoffsCancelResponses = {
  /**
   * OK
   */
  200: WriteoffDto;
};

export type WriteoffsCancelResponse = WriteoffsCancelResponses[keyof WriteoffsCancelResponses];
