// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectWarehouse.Server.Data;
using ProjectWarehouse.Server.Domain;
using ProjectWarehouse.Server.Models;

#nullable disable

namespace ProjectWarehouse.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260825154503_AddWarehouseTimeZone")]
    partial class AddWarehouseTimeZone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserWarehouse", b =>
                {
                    b.Property<Guid>("AssignedUsersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedWarehousesId")
                        .HasColumnType("uuid");

                    b.HasKey("AssignedUsersId", "AssignedWarehousesId");

                    b.HasIndex("AssignedWarehousesId");

                    b.ToTable("ApplicationUserWarehouse");
                });

            modelBuilder.Entity("CatalogItemTagLinks", b =>
                {
                    b.Property<Guid>("ItemsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("CatalogItemTagLinks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyFulfillment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ResolvedCatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskBoxComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnitInventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitInventoryNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ResolvedCatalogItemId");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TaskBoxComponentId");

                    b.HasIndex("UnitInventoryItemId");

                    b.ToTable("AssemblyFulfillments");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyFulfillmentBundleComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FulfillmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnitInventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitInventoryNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("FulfillmentId");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("UnitInventoryItemId");

                    b.ToTable("AssemblyFulfillmentBundleComponents");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("OrderId");

                    b.ToTable("AssemblyTasks");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyTaskBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssemblyTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderBoxId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyTaskId");

                    b.HasIndex("OrderBoxId");

                    b.ToTable("AssemblyTaskBoxes");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyTaskBoxComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssemblyTaskBoxId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyTaskBoxId");

                    b.HasIndex("CatalogItemId");

                    b.ToTable("AssemblyTaskBoxComponents");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.BundleComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BundleId");

                    b.HasIndex("ComponentId");

                    b.ToTable("BundleComponents");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MainImageFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("MainImageFileId");

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.CatalogItemImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataFileId");

                    b.HasIndex("CatalogItemId", "Order");

                    b.ToTable("CatalogItemImages");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.CatalogItemTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CatalogItemTags");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.CatalogItemVariationMember", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariationId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId", "VariationId");

                    b.HasIndex("VariationId");

                    b.ToTable("CatalogItemVariationMembers");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ChangeLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("ActionData")
                        .HasColumnType("jsonb");

                    b.Property<int>("ChangeLogEntryType")
                        .HasColumnType("integer");

                    b.Property<string>("Context")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IList<ChangeLogDiff>>("Diffs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<string>("Snapshot")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("UserId");

                    b.ToTable("ChangeLogEntries");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.DataFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("DataFiles");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StoragePlaceNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("StoragePlaceNodeId");

                    b.ToTable("InventoryItems");

                    b.HasDiscriminator<string>("Type").HasValue("InventoryItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ItemsGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.ToTable("ItemsGroup");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ItemsGroup");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyLast4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiKeyProtected")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApiKeyUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompanyLegalName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalClientId")
                        .HasColumnType("text");

                    b.Property<string>("Inn")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<AppFieldError>("LastSyncError")
                        .HasColumnType("jsonb");

                    b.Property<int?>("LastSyncStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ogrn")
                        .HasColumnType("text");

                    b.Property<string>("OwnershipForm")
                        .HasColumnType("text");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Type");

                    b.ToTable("MarketplaceAccounts");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceAutoMapRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Field")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Operator")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("IsEnabled", "Priority")
                        .IsDescending(false, true);

                    b.ToTable("MarketplaceAutoMapRules");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("Barcodes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MappedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MappingSource")
                        .HasColumnType("integer");

                    b.Property<Guid>("MarketplaceAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PrimaryImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("MarketplaceAccountId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("MarketplaceAccountId", "OfferId");

                    b.HasIndex("MarketplaceAccountId", "Sku");

                    b.ToTable("MarketplaceCards");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceOrder", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryMethodName")
                        .HasColumnType("text");

                    b.Property<string>("ExternalOrderNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InProcessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<AppFieldError>("LabelError")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LabelFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LabelFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarketplaceAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("MultiBoxQty")
                        .HasColumnType("integer");

                    b.Property<string>("PostingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawStatus")
                        .HasColumnType("text");

                    b.Property<string>("RawSubstatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StatusSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text");

                    b.HasKey("OrderId");

                    b.HasIndex("LabelFileId");

                    b.HasIndex("MarketplaceAccountId", "PostingNumber")
                        .IsUnique();

                    b.HasIndex("MarketplaceAccountId", "Status");

                    b.ToTable("MarketplaceOrders");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AutoMapped")
                        .HasColumnType("integer");

                    b.Property<int>("CardsArchived")
                        .HasColumnType("integer");

                    b.Property<int>("CardsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("CardsProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("CardsUpdated")
                        .HasColumnType("integer");

                    b.Property<AppFieldError>("Error")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarketplaceAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrdersCreated")
                        .HasColumnType("integer");

                    b.Property<int>("OrdersProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("OrdersSkipped")
                        .HasColumnType("integer");

                    b.Property<int>("OrdersUpdated")
                        .HasColumnType("integer");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<IList<SkippedOrderInfo>>("SkippedOrders")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TriggeredById")
                        .HasColumnType("uuid");

                    b.Property<int>("WarehousesProcessed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredById");

                    b.HasIndex("MarketplaceAccountId", "StartedAt")
                        .IsDescending(false, true);

                    b.ToTable("MarketplaceSyncRuns");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceWarehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalStatus")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("MarketplaceAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("MarketplaceAccountId", "ExternalId")
                        .IsUnique();

                    b.ToTable("MarketplaceWarehouses");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Number"));

                    b.Property<DateTime?>("PlannedShipmentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.OrderBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderBoxes");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.OrderBoxComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderBoxId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("OrderBoxId");

                    b.ToTable("OrderBoxComponents");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.OrderMarketplaceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MarketplaceCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceCardId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderMarketplaceItems");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Number"));

                    b.Property<DateOnly?>("PlannedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ReceiptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PlannedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ReceivedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptItems");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ReceiptItemPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReceiptItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoragePlaceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnitInventoryItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptItemId");

                    b.HasIndex("StoragePlaceNodeId");

                    b.HasIndex("UnitInventoryItemId");

                    b.ToTable("ReceiptItemPlacements");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .HasColumnType("text");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StoragePlaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StoragePlaceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("StoragePlaceId");

                    b.HasIndex("StoragePlaceNodeId");

                    b.HasIndex("CatalogItemId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("WarehouseId", "CreatedAt");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Stocktake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Number"));

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("Stocktakes");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StocktakeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AppliedDelta")
                        .HasColumnType("integer");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("InventoryNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("StocktakeNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnitInventoryItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("InventoryNumber");

                    b.HasIndex("StocktakeNodeId");

                    b.HasIndex("UnitInventoryItemId");

                    b.ToTable("StocktakeItems");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StocktakeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("StocktakeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoragePlaceNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoragePlaceNodeId");

                    b.HasIndex("StocktakeId", "StoragePlaceNodeId")
                        .IsUnique();

                    b.ToTable("StocktakeNodes");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StoragePlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rotation")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.Property<decimal>("X")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Y")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StoragePlaces");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StoragePlaceNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RootStoragePlaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentNodeId");

                    b.HasIndex("RootStoragePlaceId");

                    b.ToTable("StoragePlacesNodes");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Permission");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultStoragePlaceNodeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DefaultStoragePlaceNodeId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Writeoff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Number"));

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("Writeoffs");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.WriteoffItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnitInventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WriteoffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("UnitInventoryItemId");

                    b.HasIndex("WriteoffId");

                    b.ToTable("WriteoffItems");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.UnitInventoryItem", b =>
                {
                    b.HasBaseType("ProjectWarehouse.Server.Domain.InventoryItem");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CatalogItemId", "InventoryNumber")
                        .IsUnique()
                        .HasFilter("\"Type\" = 'Unit'");

                    b.HasDiscriminator().HasValue("Unit");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StoragePlaceNodeItemsGroup", b =>
                {
                    b.HasBaseType("ProjectWarehouse.Server.Domain.ItemsGroup");

                    b.Property<Guid>("StoragePlaceNodeId")
                        .HasColumnType("uuid");

                    b.HasIndex("StoragePlaceNodeId");

                    b.HasDiscriminator().HasValue("StoragePlaceNodeItemsGroup");
                });

            modelBuilder.Entity("ApplicationUserWarehouse", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("AssignedWarehousesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatalogItemTagLinks", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItemTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ApplicationUserRole", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyFulfillment", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "ResolvedCatalogItem")
                        .WithMany()
                        .HasForeignKey("ResolvedCatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlaceNode", "SourceNode")
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectWarehouse.Server.Domain.AssemblyTaskBoxComponent", "TaskBoxComponent")
                        .WithMany("Fulfillments")
                        .HasForeignKey("TaskBoxComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.UnitInventoryItem", "UnitInventoryItem")
                        .WithMany()
                        .HasForeignKey("UnitInventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("ResolvedCatalogItem");

                    b.Navigation("SourceNode");

                    b.Navigation("TaskBoxComponent");

                    b.Navigation("UnitInventoryItem");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyFulfillmentBundleComponent", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.AssemblyFulfillment", "Fulfillment")
                        .WithMany("BundleComponents")
                        .HasForeignKey("FulfillmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlaceNode", "SourceNode")
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.UnitInventoryItem", "UnitInventoryItem")
                        .WithMany()
                        .HasForeignKey("UnitInventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CatalogItem");

                    b.Navigation("Fulfillment");

                    b.Navigation("SourceNode");

                    b.Navigation("UnitInventoryItem");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyTask", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWarehouse.Server.Domain.Order", "Order")
                        .WithMany("AssemblyTasks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyTaskBox", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.AssemblyTask", "AssemblyTask")
                        .WithMany("Boxes")
                        .HasForeignKey("AssemblyTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.OrderBox", "OrderBox")
                        .WithMany()
                        .HasForeignKey("OrderBoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssemblyTask");

                    b.Navigation("OrderBox");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyTaskBoxComponent", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.AssemblyTaskBox", "AssemblyTaskBox")
                        .WithMany("Components")
                        .HasForeignKey("AssemblyTaskBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssemblyTaskBox");

                    b.Navigation("CatalogItem");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.BundleComponent", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "Bundle")
                        .WithMany("BundleComponents")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bundle");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.CatalogItem", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "Group")
                        .WithMany("GroupChildren")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectWarehouse.Server.Domain.DataFile", "MainImageFile")
                        .WithMany()
                        .HasForeignKey("MainImageFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("MainImageFile");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.CatalogItemImage", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany("Images")
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.DataFile", "DataFile")
                        .WithMany()
                        .HasForeignKey("DataFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("DataFile");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.CatalogItemVariationMember", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "Item")
                        .WithMany("VariationMemberships")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "Variation")
                        .WithMany("VariationMembers")
                        .HasForeignKey("VariationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Variation");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ChangeLogEntry", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.DataFile", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.InventoryItem", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlaceNode", "StoragePlaceNode")
                        .WithMany("InventoryItems")
                        .HasForeignKey("StoragePlaceNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CatalogItem");

                    b.Navigation("StoragePlaceNode");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ItemsGroup", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatalogItem");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceAccount", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceAutoMapRule", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatalogItem");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceCard", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany("MarketplaceCards")
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectWarehouse.Server.Domain.MarketplaceAccount", "MarketplaceAccount")
                        .WithMany("Cards")
                        .HasForeignKey("MarketplaceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("MarketplaceAccount");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceOrder", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.DataFile", "LabelFile")
                        .WithMany()
                        .HasForeignKey("LabelFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectWarehouse.Server.Domain.MarketplaceAccount", "MarketplaceAccount")
                        .WithMany("Orders")
                        .HasForeignKey("MarketplaceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.Order", "Order")
                        .WithOne("MarketplaceOrder")
                        .HasForeignKey("ProjectWarehouse.Server.Domain.MarketplaceOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabelFile");

                    b.Navigation("MarketplaceAccount");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceSyncRun", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.MarketplaceAccount", "MarketplaceAccount")
                        .WithMany("SyncRuns")
                        .HasForeignKey("MarketplaceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MarketplaceAccount");

                    b.Navigation("TriggeredBy");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceWarehouse", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.MarketplaceAccount", "MarketplaceAccount")
                        .WithMany("Warehouses")
                        .HasForeignKey("MarketplaceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.Warehouse", "Warehouse")
                        .WithMany("MarketplaceWarehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MarketplaceAccount");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Order", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWarehouse.Server.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.OrderBox", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.Order", "Order")
                        .WithMany("Boxes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.OrderBoxComponent", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.OrderBox", "OrderBox")
                        .WithMany("Components")
                        .HasForeignKey("OrderBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("OrderBox");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.OrderMarketplaceItem", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.MarketplaceCard", "MarketplaceCard")
                        .WithMany()
                        .HasForeignKey("MarketplaceCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectWarehouse.Server.Domain.Order", "Order")
                        .WithMany("MarketplaceItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketplaceCard");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Receipt", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWarehouse.Server.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ReceiptItem", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.Receipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ReceiptItemPlacement", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ReceiptItem", "ReceiptItem")
                        .WithMany("Placements")
                        .HasForeignKey("ReceiptItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlaceNode", "StoragePlaceNode")
                        .WithMany()
                        .HasForeignKey("StoragePlaceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.UnitInventoryItem", "UnitInventoryItem")
                        .WithMany()
                        .HasForeignKey("UnitInventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReceiptItem");

                    b.Navigation("StoragePlaceNode");

                    b.Navigation("UnitInventoryItem");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.RefreshToken", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.RolePermission", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StockMovement", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlace", "StoragePlace")
                        .WithMany()
                        .HasForeignKey("StoragePlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlaceNode", "StoragePlaceNode")
                        .WithMany()
                        .HasForeignKey("StoragePlaceNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWarehouse.Server.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CatalogItem");

                    b.Navigation("StoragePlace");

                    b.Navigation("StoragePlaceNode");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Stocktake", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWarehouse.Server.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StocktakeItem", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.StocktakeNode", "StocktakeNode")
                        .WithMany("Items")
                        .HasForeignKey("StocktakeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.UnitInventoryItem", "UnitInventoryItem")
                        .WithMany()
                        .HasForeignKey("UnitInventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CatalogItem");

                    b.Navigation("StocktakeNode");

                    b.Navigation("UnitInventoryItem");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StocktakeNode", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.Stocktake", "Stocktake")
                        .WithMany("Nodes")
                        .HasForeignKey("StocktakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlaceNode", "StoragePlaceNode")
                        .WithMany()
                        .HasForeignKey("StoragePlaceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stocktake");

                    b.Navigation("StoragePlaceNode");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StoragePlace", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.Warehouse", "Warehouse")
                        .WithMany("StoragePlaces")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StoragePlaceNode", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlaceNode", "ParentNode")
                        .WithMany("ChildrenNodes")
                        .HasForeignKey("ParentNodeId");

                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlace", "RootStoragePlace")
                        .WithMany("StoragePlaceNodes")
                        .HasForeignKey("RootStoragePlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentNode");

                    b.Navigation("RootStoragePlace");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.UserPermission", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Warehouse", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlaceNode", "DefaultStoragePlaceNode")
                        .WithMany()
                        .HasForeignKey("DefaultStoragePlaceNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("ProjectWarehouse.Server.Domain.WarehouseLayoutElement", "LayoutObjects", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal>("Height");

                            b1.Property<decimal>("Rotation");

                            b1.Property<int>("Type");

                            b1.Property<decimal>("Width");

                            b1.Property<decimal>("X");

                            b1.Property<decimal>("Y");

                            b1.HasKey("WarehouseId", "__synthesizedOrdinal");

                            b1.ToTable("Warehouses");

                            b1
                                .ToJson("LayoutObjects")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.Navigation("DefaultStoragePlaceNode");

                    b.Navigation("LayoutObjects");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Writeoff", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWarehouse.Server.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.WriteoffItem", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.CatalogItem", "CatalogItem")
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlaceNode", "SourceNode")
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectWarehouse.Server.Domain.UnitInventoryItem", "UnitInventoryItem")
                        .WithMany()
                        .HasForeignKey("UnitInventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectWarehouse.Server.Domain.Writeoff", "Writeoff")
                        .WithMany("Items")
                        .HasForeignKey("WriteoffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogItem");

                    b.Navigation("SourceNode");

                    b.Navigation("UnitInventoryItem");

                    b.Navigation("Writeoff");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StoragePlaceNodeItemsGroup", b =>
                {
                    b.HasOne("ProjectWarehouse.Server.Domain.StoragePlaceNode", "StoragePlaceNode")
                        .WithMany("ItemsGroups")
                        .HasForeignKey("StoragePlaceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StoragePlaceNode");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyFulfillment", b =>
                {
                    b.Navigation("BundleComponents");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyTask", b =>
                {
                    b.Navigation("Boxes");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyTaskBox", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.AssemblyTaskBoxComponent", b =>
                {
                    b.Navigation("Fulfillments");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.CatalogItem", b =>
                {
                    b.Navigation("BundleComponents");

                    b.Navigation("GroupChildren");

                    b.Navigation("Images");

                    b.Navigation("MarketplaceCards");

                    b.Navigation("VariationMembers");

                    b.Navigation("VariationMemberships");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.MarketplaceAccount", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Orders");

                    b.Navigation("SyncRuns");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Order", b =>
                {
                    b.Navigation("AssemblyTasks");

                    b.Navigation("Boxes");

                    b.Navigation("MarketplaceItems");

                    b.Navigation("MarketplaceOrder");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.OrderBox", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Receipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.ReceiptItem", b =>
                {
                    b.Navigation("Placements");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Stocktake", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StocktakeNode", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StoragePlace", b =>
                {
                    b.Navigation("StoragePlaceNodes");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.StoragePlaceNode", b =>
                {
                    b.Navigation("ChildrenNodes");

                    b.Navigation("InventoryItems");

                    b.Navigation("ItemsGroups");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Warehouse", b =>
                {
                    b.Navigation("MarketplaceWarehouses");

                    b.Navigation("StoragePlaces");
                });

            modelBuilder.Entity("ProjectWarehouse.Server.Domain.Writeoff", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
