// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import {client} from "../client.gen";
import {
  authChangeOwnPassword,
  authLogin,
  authLogout,
  authMe,
  authRefresh,
  type Options,
  permissionsGetAll,
  rolesGetAll,
  rolesSearch,
  rolesUpdateAll,
  usersChangePassword,
  usersCreate,
  usersDelete,
  usersGetAll,
  usersGetById,
  usersUpdate,
  weatherForecastGet,
} from "../sdk.gen";
import type {
  AuthChangeOwnPasswordData,
  AuthChangeOwnPasswordError,
  AuthChangeOwnPasswordResponse,
  AuthLoginData,
  AuthLoginError,
  AuthLoginResponse,
  AuthLogoutData,
  AuthLogoutError,
  AuthLogoutResponse,
  AuthMeData,
  AuthMeError,
  AuthMeResponse,
  AuthRefreshData,
  AuthRefreshError,
  AuthRefreshResponse,
  PermissionsGetAllData,
  PermissionsGetAllError,
  PermissionsGetAllResponse,
  RolesGetAllData,
  RolesGetAllError,
  RolesGetAllResponse,
  RolesSearchData,
  RolesSearchError,
  RolesSearchResponse,
  RolesUpdateAllData,
  RolesUpdateAllError,
  RolesUpdateAllResponse,
  UsersChangePasswordData,
  UsersChangePasswordError,
  UsersChangePasswordResponse,
  UsersCreateData,
  UsersCreateError,
  UsersCreateResponse,
  UsersDeleteData,
  UsersDeleteError,
  UsersDeleteResponse,
  UsersGetAllData,
  UsersGetAllError,
  UsersGetAllResponse,
  UsersGetByIdData,
  UsersGetByIdError,
  UsersGetByIdResponse,
  UsersUpdateData,
  UsersUpdateError,
  UsersUpdateResponse,
  WeatherForecastGetData,
  WeatherForecastGetResponse,
} from "../types.gen";

/**
 * Authenticate with username and password.
 */
export const authLoginMutation = (
  options?: Partial<Options<AuthLoginData>>,
): UseMutationOptions<AuthLoginResponse, AuthLoginError, Options<AuthLoginData>> => {
  const mutationOptions: UseMutationOptions<
    AuthLoginResponse,
    AuthLoginError,
    Options<AuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await authLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Refresh an access token using a valid refresh token.
 */
export const authRefreshMutation = (
  options?: Partial<Options<AuthRefreshData>>,
): UseMutationOptions<AuthRefreshResponse, AuthRefreshError, Options<AuthRefreshData>> => {
  const mutationOptions: UseMutationOptions<
    AuthRefreshResponse,
    AuthRefreshError,
    Options<AuthRefreshData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await authRefresh({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revoke the current refresh token (logout).
 */
export const authLogoutMutation = (
  options?: Partial<Options<AuthLogoutData>>,
): UseMutationOptions<AuthLogoutResponse, AuthLogoutError, Options<AuthLogoutData>> => {
  const mutationOptions: UseMutationOptions<
    AuthLogoutResponse,
    AuthLogoutError,
    Options<AuthLogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await authLogout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Change the current user's own password (requires current password).
 */
export const authChangeOwnPasswordMutation = (
  options?: Partial<Options<AuthChangeOwnPasswordData>>,
): UseMutationOptions<
  AuthChangeOwnPasswordResponse,
  AuthChangeOwnPasswordError,
  Options<AuthChangeOwnPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthChangeOwnPasswordResponse,
    AuthChangeOwnPasswordError,
    Options<AuthChangeOwnPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await authChangeOwnPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const authMeQueryKey = (options?: Options<AuthMeData>) => createQueryKey("authMe", options);

/**
 * Get the currently authenticated user's info, roles and permissions.
 */
export const authMeOptions = (options?: Options<AuthMeData>) =>
  queryOptions<AuthMeResponse, AuthMeError, AuthMeResponse, ReturnType<typeof authMeQueryKey>>({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await authMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authMeQueryKey(options),
  });

export const permissionsGetAllQueryKey = (options?: Options<PermissionsGetAllData>) =>
  createQueryKey("permissionsGetAll", options);

/**
 * Get all available static permissions defined in the system.
 */
export const permissionsGetAllOptions = (options?: Options<PermissionsGetAllData>) =>
  queryOptions<
    PermissionsGetAllResponse,
    PermissionsGetAllError,
    PermissionsGetAllResponse,
    ReturnType<typeof permissionsGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await permissionsGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: permissionsGetAllQueryKey(options),
  });

export const rolesGetAllQueryKey = (options?: Options<RolesGetAllData>) =>
  createQueryKey("rolesGetAll", options);

/**
 * List all roles with their permissions.
 */
export const rolesGetAllOptions = (options?: Options<RolesGetAllData>) =>
  queryOptions<
    RolesGetAllResponse,
    RolesGetAllError,
    RolesGetAllResponse,
    ReturnType<typeof rolesGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await rolesGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: rolesGetAllQueryKey(options),
  });

/**
 * Atomically replace the entire roles collection.
 */
export const rolesUpdateAllMutation = (
  options?: Partial<Options<RolesUpdateAllData>>,
): UseMutationOptions<RolesUpdateAllResponse, RolesUpdateAllError, Options<RolesUpdateAllData>> => {
  const mutationOptions: UseMutationOptions<
    RolesUpdateAllResponse,
    RolesUpdateAllError,
    Options<RolesUpdateAllData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await rolesUpdateAll({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const rolesSearchQueryKey = (options?: Options<RolesSearchData>) =>
  createQueryKey("rolesSearch", options);

/**
 * Search roles by name (id + name only, max 10 results).
 */
export const rolesSearchOptions = (options?: Options<RolesSearchData>) =>
  queryOptions<
    RolesSearchResponse,
    RolesSearchError,
    RolesSearchResponse,
    ReturnType<typeof rolesSearchQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await rolesSearch({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: rolesSearchQueryKey(options),
  });

export const usersGetAllQueryKey = (options?: Options<UsersGetAllData>) =>
  createQueryKey("usersGetAll", options);

/**
 * List all users (paginated).
 */
export const usersGetAllOptions = (options?: Options<UsersGetAllData>) =>
  queryOptions<
    UsersGetAllResponse,
    UsersGetAllError,
    UsersGetAllResponse,
    ReturnType<typeof usersGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await usersGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersGetAllQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {...queryKey[0]};
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const usersGetAllInfiniteQueryKey = (
  options?: Options<UsersGetAllData>,
): QueryKey<Options<UsersGetAllData>> => createQueryKey("usersGetAll", options, true);

/**
 * List all users (paginated).
 */
export const usersGetAllInfiniteOptions = (options?: Options<UsersGetAllData>) =>
  infiniteQueryOptions<
    UsersGetAllResponse,
    UsersGetAllError,
    InfiniteData<UsersGetAllResponse>,
    QueryKey<Options<UsersGetAllData>>,
    number | Pick<QueryKey<Options<UsersGetAllData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<UsersGetAllData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const {data} = await usersGetAll({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: usersGetAllInfiniteQueryKey(options),
    },
  );

/**
 * Create a new user.
 */
export const usersCreateMutation = (
  options?: Partial<Options<UsersCreateData>>,
): UseMutationOptions<UsersCreateResponse, UsersCreateError, Options<UsersCreateData>> => {
  const mutationOptions: UseMutationOptions<
    UsersCreateResponse,
    UsersCreateError,
    Options<UsersCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await usersCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a user.
 */
export const usersDeleteMutation = (
  options?: Partial<Options<UsersDeleteData>>,
): UseMutationOptions<UsersDeleteResponse, UsersDeleteError, Options<UsersDeleteData>> => {
  const mutationOptions: UseMutationOptions<
    UsersDeleteResponse,
    UsersDeleteError,
    Options<UsersDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await usersDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersGetByIdQueryKey = (options: Options<UsersGetByIdData>) =>
  createQueryKey("usersGetById", options);

/**
 * Get a user by ID.
 */
export const usersGetByIdOptions = (options: Options<UsersGetByIdData>) =>
  queryOptions<
    UsersGetByIdResponse,
    UsersGetByIdError,
    UsersGetByIdResponse,
    ReturnType<typeof usersGetByIdQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await usersGetById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersGetByIdQueryKey(options),
  });

/**
 * Update a user's profile, roles, and direct permissions atomically.
 */
export const usersUpdateMutation = (
  options?: Partial<Options<UsersUpdateData>>,
): UseMutationOptions<UsersUpdateResponse, UsersUpdateError, Options<UsersUpdateData>> => {
  const mutationOptions: UseMutationOptions<
    UsersUpdateResponse,
    UsersUpdateError,
    Options<UsersUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await usersUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reset another user's password (admin action, no current password required).
 */
export const usersChangePasswordMutation = (
  options?: Partial<Options<UsersChangePasswordData>>,
): UseMutationOptions<
  UsersChangePasswordResponse,
  UsersChangePasswordError,
  Options<UsersChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    UsersChangePasswordResponse,
    UsersChangePasswordError,
    Options<UsersChangePasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await usersChangePassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const weatherForecastGetQueryKey = (options?: Options<WeatherForecastGetData>) =>
  createQueryKey("weatherForecastGet", options);

export const weatherForecastGetOptions = (options?: Options<WeatherForecastGetData>) =>
  queryOptions<
    WeatherForecastGetResponse,
    DefaultError,
    WeatherForecastGetResponse,
    ReturnType<typeof weatherForecastGetQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await weatherForecastGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: weatherForecastGetQueryKey(options),
  });
