// This file is auto-generated by @hey-api/openapi-ts

import {
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import {client} from "../client.gen";
import {
  authChangeOwnPassword,
  authLogin,
  authLogout,
  authMe,
  authRefresh,
  catalogCreate,
  catalogCreateTag,
  catalogDelete,
  catalogGetAll,
  catalogGetById,
  catalogGetForSelect,
  catalogGetTags,
  catalogUpdate,
  changelogGetAll,
  commonContentGetHomePageContent,
  commonContentGlobalSearch,
  eventsGetEvents,
  inventoryItemsGetAll,
  inventoryItemsGetAllAssembledBundles,
  inventoryItemsGetAllUnits,
  type Options,
  permissionsGetAll,
  receiptsAddAssembledBundlePlacement,
  receiptsAddStandardPlacement,
  receiptsAddUnitPlacement,
  receiptsCancel,
  receiptsCreate,
  receiptsDelete,
  receiptsDeletePlacement,
  receiptsFinish,
  receiptsGetAll,
  receiptsGetById,
  receiptsPlan,
  receiptsRevert,
  receiptsStartProcessing,
  receiptsSyncItems,
  receiptsUpdate,
  receiptsUpdateReceivedCount,
  rolesGetAll,
  rolesGetById,
  rolesSearch,
  rolesUpdateAll,
  storagePlacesAddNode,
  storagePlacesDeleteNode,
  storagePlacesGetNodeDetails,
  storagePlacesGetNodes,
  storagePlacesReorderNodes,
  storagePlacesUpdateNode,
  transfersExecute,
  usersChangePassword,
  usersCreate,
  usersDelete,
  usersGetAll,
  usersGetById,
  usersUpdate,
  warehousesCreate,
  warehousesDelete,
  warehousesGetAll,
  warehousesGetById,
  warehousesGetByIdForPrint,
  warehousesGetDefaultNode,
  warehousesUpdate,
} from "../sdk.gen";
import type {
  AuthChangeOwnPasswordData,
  AuthChangeOwnPasswordError,
  AuthChangeOwnPasswordResponse,
  AuthLoginData,
  AuthLoginError,
  AuthLoginResponse,
  AuthLogoutData,
  AuthLogoutError,
  AuthLogoutResponse,
  AuthMeData,
  AuthMeError,
  AuthMeResponse,
  AuthRefreshData,
  AuthRefreshError,
  AuthRefreshResponse,
  CatalogCreateData,
  CatalogCreateError,
  CatalogCreateResponse,
  CatalogCreateTagData,
  CatalogCreateTagError,
  CatalogCreateTagResponse,
  CatalogDeleteData,
  CatalogDeleteError,
  CatalogDeleteResponse,
  CatalogGetAllData,
  CatalogGetAllError,
  CatalogGetAllResponse,
  CatalogGetByIdData,
  CatalogGetByIdError,
  CatalogGetByIdResponse,
  CatalogGetForSelectData,
  CatalogGetForSelectError,
  CatalogGetForSelectResponse,
  CatalogGetTagsData,
  CatalogGetTagsError,
  CatalogGetTagsResponse,
  CatalogUpdateData,
  CatalogUpdateError,
  CatalogUpdateResponse,
  ChangelogGetAllData,
  ChangelogGetAllError,
  ChangelogGetAllResponse,
  CommonContentGetHomePageContentData,
  CommonContentGetHomePageContentError,
  CommonContentGetHomePageContentResponse,
  CommonContentGlobalSearchData,
  CommonContentGlobalSearchError,
  CommonContentGlobalSearchResponse,
  EventsGetEventsData,
  EventsGetEventsError,
  EventsGetEventsResponse,
  InventoryItemsGetAllAssembledBundlesData,
  InventoryItemsGetAllAssembledBundlesError,
  InventoryItemsGetAllAssembledBundlesResponse,
  InventoryItemsGetAllData,
  InventoryItemsGetAllError,
  InventoryItemsGetAllResponse,
  InventoryItemsGetAllUnitsData,
  InventoryItemsGetAllUnitsError,
  InventoryItemsGetAllUnitsResponse,
  PermissionsGetAllData,
  PermissionsGetAllError,
  PermissionsGetAllResponse,
  ReceiptsAddAssembledBundlePlacementData,
  ReceiptsAddAssembledBundlePlacementError,
  ReceiptsAddAssembledBundlePlacementResponse,
  ReceiptsAddStandardPlacementData,
  ReceiptsAddStandardPlacementError,
  ReceiptsAddStandardPlacementResponse,
  ReceiptsAddUnitPlacementData,
  ReceiptsAddUnitPlacementError,
  ReceiptsAddUnitPlacementResponse,
  ReceiptsCancelData,
  ReceiptsCancelError,
  ReceiptsCancelResponse,
  ReceiptsCreateData,
  ReceiptsCreateError,
  ReceiptsCreateResponse,
  ReceiptsDeleteData,
  ReceiptsDeleteError,
  ReceiptsDeletePlacementData,
  ReceiptsDeletePlacementError,
  ReceiptsDeletePlacementResponse,
  ReceiptsDeleteResponse,
  ReceiptsFinishData,
  ReceiptsFinishError,
  ReceiptsFinishResponse,
  ReceiptsGetAllData,
  ReceiptsGetAllError,
  ReceiptsGetAllResponse,
  ReceiptsGetByIdData,
  ReceiptsGetByIdError,
  ReceiptsGetByIdResponse,
  ReceiptsPlanData,
  ReceiptsPlanError,
  ReceiptsPlanResponse,
  ReceiptsRevertData,
  ReceiptsRevertError,
  ReceiptsRevertResponse,
  ReceiptsStartProcessingData,
  ReceiptsStartProcessingError,
  ReceiptsStartProcessingResponse,
  ReceiptsSyncItemsData,
  ReceiptsSyncItemsError,
  ReceiptsSyncItemsResponse,
  ReceiptsUpdateData,
  ReceiptsUpdateError,
  ReceiptsUpdateReceivedCountData,
  ReceiptsUpdateReceivedCountError,
  ReceiptsUpdateReceivedCountResponse,
  ReceiptsUpdateResponse,
  RolesGetAllData,
  RolesGetAllError,
  RolesGetAllResponse,
  RolesGetByIdData,
  RolesGetByIdError,
  RolesGetByIdResponse,
  RolesSearchData,
  RolesSearchError,
  RolesSearchResponse,
  RolesUpdateAllData,
  RolesUpdateAllError,
  RolesUpdateAllResponse,
  StoragePlacesAddNodeData,
  StoragePlacesAddNodeError,
  StoragePlacesAddNodeResponse,
  StoragePlacesDeleteNodeData,
  StoragePlacesDeleteNodeError,
  StoragePlacesDeleteNodeResponse,
  StoragePlacesGetNodeDetailsData,
  StoragePlacesGetNodeDetailsError,
  StoragePlacesGetNodeDetailsResponse,
  StoragePlacesGetNodesData,
  StoragePlacesGetNodesError,
  StoragePlacesGetNodesResponse,
  StoragePlacesReorderNodesData,
  StoragePlacesReorderNodesError,
  StoragePlacesReorderNodesResponse,
  StoragePlacesUpdateNodeData,
  StoragePlacesUpdateNodeError,
  StoragePlacesUpdateNodeResponse,
  TransfersExecuteData,
  TransfersExecuteError,
  TransfersExecuteResponse,
  UsersChangePasswordData,
  UsersChangePasswordError,
  UsersChangePasswordResponse,
  UsersCreateData,
  UsersCreateError,
  UsersCreateResponse,
  UsersDeleteData,
  UsersDeleteError,
  UsersDeleteResponse,
  UsersGetAllData,
  UsersGetAllError,
  UsersGetAllResponse,
  UsersGetByIdData,
  UsersGetByIdError,
  UsersGetByIdResponse,
  UsersUpdateData,
  UsersUpdateError,
  UsersUpdateResponse,
  WarehousesCreateData,
  WarehousesCreateError,
  WarehousesCreateResponse,
  WarehousesDeleteData,
  WarehousesDeleteError,
  WarehousesDeleteResponse,
  WarehousesGetAllData,
  WarehousesGetAllError,
  WarehousesGetAllResponse,
  WarehousesGetByIdData,
  WarehousesGetByIdError,
  WarehousesGetByIdForPrintData,
  WarehousesGetByIdForPrintError,
  WarehousesGetByIdForPrintResponse,
  WarehousesGetByIdResponse,
  WarehousesGetDefaultNodeData,
  WarehousesGetDefaultNodeError,
  WarehousesGetDefaultNodeResponse,
  WarehousesUpdateData,
  WarehousesUpdateError,
  WarehousesUpdateResponse,
} from "../types.gen";

/**
 * Authenticate with username and password.
 */
export const authLoginMutation = (
  options?: Partial<Options<AuthLoginData>>,
): UseMutationOptions<AuthLoginResponse, AuthLoginError, Options<AuthLoginData>> => {
  const mutationOptions: UseMutationOptions<
    AuthLoginResponse,
    AuthLoginError,
    Options<AuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await authLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Refresh an access token using a valid refresh token.
 */
export const authRefreshMutation = (
  options?: Partial<Options<AuthRefreshData>>,
): UseMutationOptions<AuthRefreshResponse, AuthRefreshError, Options<AuthRefreshData>> => {
  const mutationOptions: UseMutationOptions<
    AuthRefreshResponse,
    AuthRefreshError,
    Options<AuthRefreshData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await authRefresh({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revoke the current refresh token (logout).
 */
export const authLogoutMutation = (
  options?: Partial<Options<AuthLogoutData>>,
): UseMutationOptions<AuthLogoutResponse, AuthLogoutError, Options<AuthLogoutData>> => {
  const mutationOptions: UseMutationOptions<
    AuthLogoutResponse,
    AuthLogoutError,
    Options<AuthLogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await authLogout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Change the current user's own password (requires current password).
 */
export const authChangeOwnPasswordMutation = (
  options?: Partial<Options<AuthChangeOwnPasswordData>>,
): UseMutationOptions<
  AuthChangeOwnPasswordResponse,
  AuthChangeOwnPasswordError,
  Options<AuthChangeOwnPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    AuthChangeOwnPasswordResponse,
    AuthChangeOwnPasswordError,
    Options<AuthChangeOwnPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await authChangeOwnPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const authMeQueryKey = (options?: Options<AuthMeData>) => createQueryKey("authMe", options);

/**
 * Get the currently authenticated user's info, roles and permissions.
 */
export const authMeOptions = (options?: Options<AuthMeData>) =>
  queryOptions<AuthMeResponse, AuthMeError, AuthMeResponse, ReturnType<typeof authMeQueryKey>>({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await authMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: authMeQueryKey(options),
  });

export const catalogGetTagsQueryKey = (options?: Options<CatalogGetTagsData>) =>
  createQueryKey("catalogGetTags", options);

/**
 * List all catalog item tags, optionally filtered by name.
 */
export const catalogGetTagsOptions = (options?: Options<CatalogGetTagsData>) =>
  queryOptions<
    CatalogGetTagsResponse,
    CatalogGetTagsError,
    CatalogGetTagsResponse,
    ReturnType<typeof catalogGetTagsQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await catalogGetTags({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: catalogGetTagsQueryKey(options),
  });

/**
 * Create a new catalog item tag.
 */
export const catalogCreateTagMutation = (
  options?: Partial<Options<CatalogCreateTagData>>,
): UseMutationOptions<
  CatalogCreateTagResponse,
  CatalogCreateTagError,
  Options<CatalogCreateTagData>
> => {
  const mutationOptions: UseMutationOptions<
    CatalogCreateTagResponse,
    CatalogCreateTagError,
    Options<CatalogCreateTagData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await catalogCreateTag({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const catalogGetAllQueryKey = (options?: Options<CatalogGetAllData>) =>
  createQueryKey("catalogGetAll", options);

/**
 * List all catalog items (paginated, optionally filtered by name).
 */
export const catalogGetAllOptions = (options?: Options<CatalogGetAllData>) =>
  queryOptions<
    CatalogGetAllResponse,
    CatalogGetAllError,
    CatalogGetAllResponse,
    ReturnType<typeof catalogGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await catalogGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: catalogGetAllQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {...queryKey[0]};
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const catalogGetAllInfiniteQueryKey = (
  options?: Options<CatalogGetAllData>,
): QueryKey<Options<CatalogGetAllData>> => createQueryKey("catalogGetAll", options, true);

/**
 * List all catalog items (paginated, optionally filtered by name).
 */
export const catalogGetAllInfiniteOptions = (options?: Options<CatalogGetAllData>) =>
  infiniteQueryOptions<
    CatalogGetAllResponse,
    CatalogGetAllError,
    InfiniteData<CatalogGetAllResponse>,
    QueryKey<Options<CatalogGetAllData>>,
    number | Pick<QueryKey<Options<CatalogGetAllData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<CatalogGetAllData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const {data} = await catalogGetAll({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: catalogGetAllInfiniteQueryKey(options),
    },
  );

/**
 * Create a new catalog item.
 */
export const catalogCreateMutation = (
  options?: Partial<Options<CatalogCreateData>>,
): UseMutationOptions<CatalogCreateResponse, CatalogCreateError, Options<CatalogCreateData>> => {
  const mutationOptions: UseMutationOptions<
    CatalogCreateResponse,
    CatalogCreateError,
    Options<CatalogCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await catalogCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const catalogGetForSelectQueryKey = (options?: Options<CatalogGetForSelectData>) =>
  createQueryKey("catalogGetForSelect", options);

/**
 * Get a flat list of catalog items for use in select/autocomplete controls.
 *
 * Returns at most 50 items. Excludes product-group children. Optionally filtered by types.
 */
export const catalogGetForSelectOptions = (options?: Options<CatalogGetForSelectData>) =>
  queryOptions<
    CatalogGetForSelectResponse,
    CatalogGetForSelectError,
    CatalogGetForSelectResponse,
    ReturnType<typeof catalogGetForSelectQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await catalogGetForSelect({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: catalogGetForSelectQueryKey(options),
  });

/**
 * Delete a catalog item.
 *
 * Returns 409 `catalogItemIsInUse` if the item is currently stored in any warehouse.
 */
export const catalogDeleteMutation = (
  options?: Partial<Options<CatalogDeleteData>>,
): UseMutationOptions<CatalogDeleteResponse, CatalogDeleteError, Options<CatalogDeleteData>> => {
  const mutationOptions: UseMutationOptions<
    CatalogDeleteResponse,
    CatalogDeleteError,
    Options<CatalogDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await catalogDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const catalogGetByIdQueryKey = (options: Options<CatalogGetByIdData>) =>
  createQueryKey("catalogGetById", options);

/**
 * Get a catalog item by ID.
 */
export const catalogGetByIdOptions = (options: Options<CatalogGetByIdData>) =>
  queryOptions<
    CatalogGetByIdResponse,
    CatalogGetByIdError,
    CatalogGetByIdResponse,
    ReturnType<typeof catalogGetByIdQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await catalogGetById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: catalogGetByIdQueryKey(options),
  });

/**
 * Update a catalog item.
 *
 *     Assembled bundles are immutable and cannot be updated (returns 422).
 * Type-specific fields:
 * * Standard / Unit: groupId, variationIds (full replace)
 * * Variation: memberIds (full replace)
 * * Bundle: components — id: null creates, id present updates, missing existing entries are deleted
 */
export const catalogUpdateMutation = (
  options?: Partial<Options<CatalogUpdateData>>,
): UseMutationOptions<CatalogUpdateResponse, CatalogUpdateError, Options<CatalogUpdateData>> => {
  const mutationOptions: UseMutationOptions<
    CatalogUpdateResponse,
    CatalogUpdateError,
    Options<CatalogUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await catalogUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const changelogGetAllQueryKey = (options?: Options<ChangelogGetAllData>) =>
  createQueryKey("changelogGetAll", options);

/**
 * List changelog entries (paginated).
 *
 * Query params: `page` (default 1), `pageSize` (default 20, max 200),
 * `entityType` (optional), `changeLogEntryType` (optional).
 * Returns `Paginated&lt;ChangeLogEntryDto&gt;` ordered by `createdAt` descending.
 */
export const changelogGetAllOptions = (options?: Options<ChangelogGetAllData>) =>
  queryOptions<
    ChangelogGetAllResponse,
    ChangelogGetAllError,
    ChangelogGetAllResponse,
    ReturnType<typeof changelogGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await changelogGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: changelogGetAllQueryKey(options),
  });

export const changelogGetAllInfiniteQueryKey = (
  options?: Options<ChangelogGetAllData>,
): QueryKey<Options<ChangelogGetAllData>> => createQueryKey("changelogGetAll", options, true);

/**
 * List changelog entries (paginated).
 *
 * Query params: `page` (default 1), `pageSize` (default 20, max 200),
 * `entityType` (optional), `changeLogEntryType` (optional).
 * Returns `Paginated&lt;ChangeLogEntryDto&gt;` ordered by `createdAt` descending.
 */
export const changelogGetAllInfiniteOptions = (options?: Options<ChangelogGetAllData>) =>
  infiniteQueryOptions<
    ChangelogGetAllResponse,
    ChangelogGetAllError,
    InfiniteData<ChangelogGetAllResponse>,
    QueryKey<Options<ChangelogGetAllData>>,
    number | Pick<QueryKey<Options<ChangelogGetAllData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ChangelogGetAllData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const {data} = await changelogGetAll({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: changelogGetAllInfiniteQueryKey(options),
    },
  );

export const commonContentGetHomePageContentQueryKey = (
  options?: Options<CommonContentGetHomePageContentData>,
) => createQueryKey("commonContentGetHomePageContent", options);

/**
 * Get list of AppEntities for home page.
 */
export const commonContentGetHomePageContentOptions = (
  options?: Options<CommonContentGetHomePageContentData>,
) =>
  queryOptions<
    CommonContentGetHomePageContentResponse,
    CommonContentGetHomePageContentError,
    CommonContentGetHomePageContentResponse,
    ReturnType<typeof commonContentGetHomePageContentQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await commonContentGetHomePageContent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: commonContentGetHomePageContentQueryKey(options),
  });

export const commonContentGlobalSearchQueryKey = (
  options?: Options<CommonContentGlobalSearchData>,
) => createQueryKey("commonContentGlobalSearch", options);

/**
 * Global search for entities.
 */
export const commonContentGlobalSearchOptions = (
  options?: Options<CommonContentGlobalSearchData>,
) =>
  queryOptions<
    CommonContentGlobalSearchResponse,
    CommonContentGlobalSearchError,
    CommonContentGlobalSearchResponse,
    ReturnType<typeof commonContentGlobalSearchQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await commonContentGlobalSearch({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: commonContentGlobalSearchQueryKey(options),
  });

export const eventsGetEventsQueryKey = (options?: Options<EventsGetEventsData>) =>
  createQueryKey("eventsGetEvents", options);

export const eventsGetEventsOptions = (options?: Options<EventsGetEventsData>) =>
  queryOptions<
    EventsGetEventsResponse,
    EventsGetEventsError,
    EventsGetEventsResponse,
    ReturnType<typeof eventsGetEventsQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await eventsGetEvents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: eventsGetEventsQueryKey(options),
  });

export const inventoryItemsGetAllQueryKey = (options?: Options<InventoryItemsGetAllData>) =>
  createQueryKey("inventoryItemsGetAll", options);

/**
 * List all inventory items aggregated by catalog item.
 *
 * Returns one row per distinct CatalogItem with a total Count summed across all three item kinds
 * (Standard, Unit, AssembledBundle). Supports filtering by warehouse, storage place, node,
 * catalog item type, and archive state.
 */
export const inventoryItemsGetAllOptions = (options?: Options<InventoryItemsGetAllData>) =>
  queryOptions<
    InventoryItemsGetAllResponse,
    InventoryItemsGetAllError,
    InventoryItemsGetAllResponse,
    ReturnType<typeof inventoryItemsGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await inventoryItemsGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: inventoryItemsGetAllQueryKey(options),
  });

export const inventoryItemsGetAllInfiniteQueryKey = (
  options?: Options<InventoryItemsGetAllData>,
): QueryKey<Options<InventoryItemsGetAllData>> =>
  createQueryKey("inventoryItemsGetAll", options, true);

/**
 * List all inventory items aggregated by catalog item.
 *
 * Returns one row per distinct CatalogItem with a total Count summed across all three item kinds
 * (Standard, Unit, AssembledBundle). Supports filtering by warehouse, storage place, node,
 * catalog item type, and archive state.
 */
export const inventoryItemsGetAllInfiniteOptions = (options?: Options<InventoryItemsGetAllData>) =>
  infiniteQueryOptions<
    InventoryItemsGetAllResponse,
    InventoryItemsGetAllError,
    InfiniteData<InventoryItemsGetAllResponse>,
    QueryKey<Options<InventoryItemsGetAllData>>,
    | number
    | Pick<QueryKey<Options<InventoryItemsGetAllData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<InventoryItemsGetAllData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const {data} = await inventoryItemsGetAll({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: inventoryItemsGetAllInfiniteQueryKey(options),
    },
  );

export const inventoryItemsGetAllUnitsQueryKey = (
  options?: Options<InventoryItemsGetAllUnitsData>,
) => createQueryKey("inventoryItemsGetAllUnits", options);

/**
 * List all unit inventory items (individual serialized items).
 */
export const inventoryItemsGetAllUnitsOptions = (
  options?: Options<InventoryItemsGetAllUnitsData>,
) =>
  queryOptions<
    InventoryItemsGetAllUnitsResponse,
    InventoryItemsGetAllUnitsError,
    InventoryItemsGetAllUnitsResponse,
    ReturnType<typeof inventoryItemsGetAllUnitsQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await inventoryItemsGetAllUnits({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: inventoryItemsGetAllUnitsQueryKey(options),
  });

export const inventoryItemsGetAllUnitsInfiniteQueryKey = (
  options?: Options<InventoryItemsGetAllUnitsData>,
): QueryKey<Options<InventoryItemsGetAllUnitsData>> =>
  createQueryKey("inventoryItemsGetAllUnits", options, true);

/**
 * List all unit inventory items (individual serialized items).
 */
export const inventoryItemsGetAllUnitsInfiniteOptions = (
  options?: Options<InventoryItemsGetAllUnitsData>,
) =>
  infiniteQueryOptions<
    InventoryItemsGetAllUnitsResponse,
    InventoryItemsGetAllUnitsError,
    InfiniteData<InventoryItemsGetAllUnitsResponse>,
    QueryKey<Options<InventoryItemsGetAllUnitsData>>,
    | number
    | Pick<
        QueryKey<Options<InventoryItemsGetAllUnitsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<InventoryItemsGetAllUnitsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const {data} = await inventoryItemsGetAllUnits({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: inventoryItemsGetAllUnitsInfiniteQueryKey(options),
    },
  );

export const inventoryItemsGetAllAssembledBundlesQueryKey = (
  options?: Options<InventoryItemsGetAllAssembledBundlesData>,
) => createQueryKey("inventoryItemsGetAllAssembledBundles", options);

/**
 * List all assembled bundle inventory items (individual bundle instances).
 */
export const inventoryItemsGetAllAssembledBundlesOptions = (
  options?: Options<InventoryItemsGetAllAssembledBundlesData>,
) =>
  queryOptions<
    InventoryItemsGetAllAssembledBundlesResponse,
    InventoryItemsGetAllAssembledBundlesError,
    InventoryItemsGetAllAssembledBundlesResponse,
    ReturnType<typeof inventoryItemsGetAllAssembledBundlesQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await inventoryItemsGetAllAssembledBundles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: inventoryItemsGetAllAssembledBundlesQueryKey(options),
  });

export const inventoryItemsGetAllAssembledBundlesInfiniteQueryKey = (
  options?: Options<InventoryItemsGetAllAssembledBundlesData>,
): QueryKey<Options<InventoryItemsGetAllAssembledBundlesData>> =>
  createQueryKey("inventoryItemsGetAllAssembledBundles", options, true);

/**
 * List all assembled bundle inventory items (individual bundle instances).
 */
export const inventoryItemsGetAllAssembledBundlesInfiniteOptions = (
  options?: Options<InventoryItemsGetAllAssembledBundlesData>,
) =>
  infiniteQueryOptions<
    InventoryItemsGetAllAssembledBundlesResponse,
    InventoryItemsGetAllAssembledBundlesError,
    InfiniteData<InventoryItemsGetAllAssembledBundlesResponse>,
    QueryKey<Options<InventoryItemsGetAllAssembledBundlesData>>,
    | number
    | Pick<
        QueryKey<Options<InventoryItemsGetAllAssembledBundlesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<InventoryItemsGetAllAssembledBundlesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const {data} = await inventoryItemsGetAllAssembledBundles({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: inventoryItemsGetAllAssembledBundlesInfiniteQueryKey(options),
    },
  );

export const permissionsGetAllQueryKey = (options?: Options<PermissionsGetAllData>) =>
  createQueryKey("permissionsGetAll", options);

/**
 * Get all available static permissions defined in the system.
 */
export const permissionsGetAllOptions = (options?: Options<PermissionsGetAllData>) =>
  queryOptions<
    PermissionsGetAllResponse,
    PermissionsGetAllError,
    PermissionsGetAllResponse,
    ReturnType<typeof permissionsGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await permissionsGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: permissionsGetAllQueryKey(options),
  });

export const receiptsGetAllQueryKey = (options?: Options<ReceiptsGetAllData>) =>
  createQueryKey("receiptsGetAll", options);

/**
 * List receipts with pagination, filtering, and search.
 */
export const receiptsGetAllOptions = (options?: Options<ReceiptsGetAllData>) =>
  queryOptions<
    ReceiptsGetAllResponse,
    ReceiptsGetAllError,
    ReceiptsGetAllResponse,
    ReturnType<typeof receiptsGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await receiptsGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: receiptsGetAllQueryKey(options),
  });

export const receiptsGetAllInfiniteQueryKey = (
  options?: Options<ReceiptsGetAllData>,
): QueryKey<Options<ReceiptsGetAllData>> => createQueryKey("receiptsGetAll", options, true);

/**
 * List receipts with pagination, filtering, and search.
 */
export const receiptsGetAllInfiniteOptions = (options?: Options<ReceiptsGetAllData>) =>
  infiniteQueryOptions<
    ReceiptsGetAllResponse,
    ReceiptsGetAllError,
    InfiniteData<ReceiptsGetAllResponse>,
    QueryKey<Options<ReceiptsGetAllData>>,
    number | Pick<QueryKey<Options<ReceiptsGetAllData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ReceiptsGetAllData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const {data} = await receiptsGetAll({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: receiptsGetAllInfiniteQueryKey(options),
    },
  );

/**
 * Create a new receipt in Draft status.
 */
export const receiptsCreateMutation = (
  options?: Partial<Options<ReceiptsCreateData>>,
): UseMutationOptions<ReceiptsCreateResponse, ReceiptsCreateError, Options<ReceiptsCreateData>> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsCreateResponse,
    ReceiptsCreateError,
    Options<ReceiptsCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a receipt. Only allowed in Draft status.
 */
export const receiptsDeleteMutation = (
  options?: Partial<Options<ReceiptsDeleteData>>,
): UseMutationOptions<ReceiptsDeleteResponse, ReceiptsDeleteError, Options<ReceiptsDeleteData>> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsDeleteResponse,
    ReceiptsDeleteError,
    Options<ReceiptsDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const receiptsGetByIdQueryKey = (options: Options<ReceiptsGetByIdData>) =>
  createQueryKey("receiptsGetById", options);

/**
 * Get full receipt details including items and placements.
 */
export const receiptsGetByIdOptions = (options: Options<ReceiptsGetByIdData>) =>
  queryOptions<
    ReceiptsGetByIdResponse,
    ReceiptsGetByIdError,
    ReceiptsGetByIdResponse,
    ReturnType<typeof receiptsGetByIdQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await receiptsGetById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: receiptsGetByIdQueryKey(options),
  });

/**
 * Update receipt name, reason, notes. Only allowed in Draft status.
 */
export const receiptsUpdateMutation = (
  options?: Partial<Options<ReceiptsUpdateData>>,
): UseMutationOptions<ReceiptsUpdateResponse, ReceiptsUpdateError, Options<ReceiptsUpdateData>> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsUpdateResponse,
    ReceiptsUpdateError,
    Options<ReceiptsUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Replace the full list of expected items. Allowed in Draft and Planned statuses.
 */
export const receiptsSyncItemsMutation = (
  options?: Partial<Options<ReceiptsSyncItemsData>>,
): UseMutationOptions<
  ReceiptsSyncItemsResponse,
  ReceiptsSyncItemsError,
  Options<ReceiptsSyncItemsData>
> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsSyncItemsResponse,
    ReceiptsSyncItemsError,
    Options<ReceiptsSyncItemsData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsSyncItems({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update the actually received count for a specific item. Only in Processing status.
 */
export const receiptsUpdateReceivedCountMutation = (
  options?: Partial<Options<ReceiptsUpdateReceivedCountData>>,
): UseMutationOptions<
  ReceiptsUpdateReceivedCountResponse,
  ReceiptsUpdateReceivedCountError,
  Options<ReceiptsUpdateReceivedCountData>
> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsUpdateReceivedCountResponse,
    ReceiptsUpdateReceivedCountError,
    Options<ReceiptsUpdateReceivedCountData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsUpdateReceivedCount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Place Standard (count-based) items at a storage node. Only in Processing status.
 */
export const receiptsAddStandardPlacementMutation = (
  options?: Partial<Options<ReceiptsAddStandardPlacementData>>,
): UseMutationOptions<
  ReceiptsAddStandardPlacementResponse,
  ReceiptsAddStandardPlacementError,
  Options<ReceiptsAddStandardPlacementData>
> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsAddStandardPlacementResponse,
    ReceiptsAddStandardPlacementError,
    Options<ReceiptsAddStandardPlacementData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsAddStandardPlacement({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Place a Unit (serialised) item at a storage node. Only in Processing status.
 */
export const receiptsAddUnitPlacementMutation = (
  options?: Partial<Options<ReceiptsAddUnitPlacementData>>,
): UseMutationOptions<
  ReceiptsAddUnitPlacementResponse,
  ReceiptsAddUnitPlacementError,
  Options<ReceiptsAddUnitPlacementData>
> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsAddUnitPlacementResponse,
    ReceiptsAddUnitPlacementError,
    Options<ReceiptsAddUnitPlacementData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsAddUnitPlacement({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Place an AssembledBundle item at a storage node. Only in Processing status.
 */
export const receiptsAddAssembledBundlePlacementMutation = (
  options?: Partial<Options<ReceiptsAddAssembledBundlePlacementData>>,
): UseMutationOptions<
  ReceiptsAddAssembledBundlePlacementResponse,
  ReceiptsAddAssembledBundlePlacementError,
  Options<ReceiptsAddAssembledBundlePlacementData>
> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsAddAssembledBundlePlacementResponse,
    ReceiptsAddAssembledBundlePlacementError,
    Options<ReceiptsAddAssembledBundlePlacementData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsAddAssembledBundlePlacement({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove a placement, reversing the inventory change. Only in Processing status.
 */
export const receiptsDeletePlacementMutation = (
  options?: Partial<Options<ReceiptsDeletePlacementData>>,
): UseMutationOptions<
  ReceiptsDeletePlacementResponse,
  ReceiptsDeletePlacementError,
  Options<ReceiptsDeletePlacementData>
> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsDeletePlacementResponse,
    ReceiptsDeletePlacementError,
    Options<ReceiptsDeletePlacementData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsDeletePlacement({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Transition: Draft → Planned.
 */
export const receiptsPlanMutation = (
  options?: Partial<Options<ReceiptsPlanData>>,
): UseMutationOptions<ReceiptsPlanResponse, ReceiptsPlanError, Options<ReceiptsPlanData>> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsPlanResponse,
    ReceiptsPlanError,
    Options<ReceiptsPlanData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsPlan({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Transition: Planned → Processing.
 */
export const receiptsStartProcessingMutation = (
  options?: Partial<Options<ReceiptsStartProcessingData>>,
): UseMutationOptions<
  ReceiptsStartProcessingResponse,
  ReceiptsStartProcessingError,
  Options<ReceiptsStartProcessingData>
> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsStartProcessingResponse,
    ReceiptsStartProcessingError,
    Options<ReceiptsStartProcessingData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsStartProcessing({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Transition: Processing → Finished. Validates that each item with a received count has enough placements.
 */
export const receiptsFinishMutation = (
  options?: Partial<Options<ReceiptsFinishData>>,
): UseMutationOptions<ReceiptsFinishResponse, ReceiptsFinishError, Options<ReceiptsFinishData>> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsFinishResponse,
    ReceiptsFinishError,
    Options<ReceiptsFinishData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsFinish({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revert one step back (Planned → Draft, Processing → Planned if no placements).
 */
export const receiptsRevertMutation = (
  options?: Partial<Options<ReceiptsRevertData>>,
): UseMutationOptions<ReceiptsRevertResponse, ReceiptsRevertError, Options<ReceiptsRevertData>> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsRevertResponse,
    ReceiptsRevertError,
    Options<ReceiptsRevertData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsRevert({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Cancel the receipt. Allowed from Draft, Planned, and Processing (if no placements).
 */
export const receiptsCancelMutation = (
  options?: Partial<Options<ReceiptsCancelData>>,
): UseMutationOptions<ReceiptsCancelResponse, ReceiptsCancelError, Options<ReceiptsCancelData>> => {
  const mutationOptions: UseMutationOptions<
    ReceiptsCancelResponse,
    ReceiptsCancelError,
    Options<ReceiptsCancelData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await receiptsCancel({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const rolesGetAllQueryKey = (options?: Options<RolesGetAllData>) =>
  createQueryKey("rolesGetAll", options);

/**
 * List all roles with their permissions.
 */
export const rolesGetAllOptions = (options?: Options<RolesGetAllData>) =>
  queryOptions<
    RolesGetAllResponse,
    RolesGetAllError,
    RolesGetAllResponse,
    ReturnType<typeof rolesGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await rolesGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: rolesGetAllQueryKey(options),
  });

/**
 * Atomically replace the entire roles collection.
 */
export const rolesUpdateAllMutation = (
  options?: Partial<Options<RolesUpdateAllData>>,
): UseMutationOptions<RolesUpdateAllResponse, RolesUpdateAllError, Options<RolesUpdateAllData>> => {
  const mutationOptions: UseMutationOptions<
    RolesUpdateAllResponse,
    RolesUpdateAllError,
    Options<RolesUpdateAllData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await rolesUpdateAll({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const rolesSearchQueryKey = (options?: Options<RolesSearchData>) =>
  createQueryKey("rolesSearch", options);

/**
 * Search roles by name (id + name only, max 10 results).
 */
export const rolesSearchOptions = (options?: Options<RolesSearchData>) =>
  queryOptions<
    RolesSearchResponse,
    RolesSearchError,
    RolesSearchResponse,
    ReturnType<typeof rolesSearchQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await rolesSearch({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: rolesSearchQueryKey(options),
  });

export const rolesGetByIdQueryKey = (options: Options<RolesGetByIdData>) =>
  createQueryKey("rolesGetById", options);

/**
 * Get a role by ID.
 */
export const rolesGetByIdOptions = (options: Options<RolesGetByIdData>) =>
  queryOptions<
    RolesGetByIdResponse,
    RolesGetByIdError,
    RolesGetByIdResponse,
    ReturnType<typeof rolesGetByIdQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await rolesGetById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: rolesGetByIdQueryKey(options),
  });

export const storagePlacesGetNodesQueryKey = (options: Options<StoragePlacesGetNodesData>) =>
  createQueryKey("storagePlacesGetNodes", options);

/**
 * Get a flat list of all nodes for a storage place.
 *
 * Returns `StoragePlaceNodeDto[]` ordered by order then name — id, name, parentNodeId (null = root), order.
 */
export const storagePlacesGetNodesOptions = (options: Options<StoragePlacesGetNodesData>) =>
  queryOptions<
    StoragePlacesGetNodesResponse,
    StoragePlacesGetNodesError,
    StoragePlacesGetNodesResponse,
    ReturnType<typeof storagePlacesGetNodesQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await storagePlacesGetNodes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: storagePlacesGetNodesQueryKey(options),
  });

/**
 * Add a node to a storage place.
 *
 * Body: `CreateStoragePlaceNodeRequest` — name (required), parentNodeId (optional, null = root node).
 * Returns the updated flat list.
 * Returns 422 `storagePlaceNodeNotFound` (field: `parentNodeId`) if the parent does not belong to this storage place.
 */
export const storagePlacesAddNodeMutation = (
  options?: Partial<Options<StoragePlacesAddNodeData>>,
): UseMutationOptions<
  StoragePlacesAddNodeResponse,
  StoragePlacesAddNodeError,
  Options<StoragePlacesAddNodeData>
> => {
  const mutationOptions: UseMutationOptions<
    StoragePlacesAddNodeResponse,
    StoragePlacesAddNodeError,
    Options<StoragePlacesAddNodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await storagePlacesAddNode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a node. Fails if the node has children — delete them first.
 *
 * Returns the updated flat list on success.
 */
export const storagePlacesDeleteNodeMutation = (
  options?: Partial<Options<StoragePlacesDeleteNodeData>>,
): UseMutationOptions<
  StoragePlacesDeleteNodeResponse,
  StoragePlacesDeleteNodeError,
  Options<StoragePlacesDeleteNodeData>
> => {
  const mutationOptions: UseMutationOptions<
    StoragePlacesDeleteNodeResponse,
    StoragePlacesDeleteNodeError,
    Options<StoragePlacesDeleteNodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await storagePlacesDeleteNode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const storagePlacesGetNodeDetailsQueryKey = (
  options: Options<StoragePlacesGetNodeDetailsData>,
) => createQueryKey("storagePlacesGetNodeDetails", options);

/**
 * Get a node by ID.
 */
export const storagePlacesGetNodeDetailsOptions = (
  options: Options<StoragePlacesGetNodeDetailsData>,
) =>
  queryOptions<
    StoragePlacesGetNodeDetailsResponse,
    StoragePlacesGetNodeDetailsError,
    StoragePlacesGetNodeDetailsResponse,
    ReturnType<typeof storagePlacesGetNodeDetailsQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await storagePlacesGetNodeDetails({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: storagePlacesGetNodeDetailsQueryKey(options),
  });

/**
 * Update a node's name or parent.
 *
 * Body: `UpdateStoragePlaceNodeRequest` — name (required), parentNodeId (nullable, null = root node).
 * Returns the updated flat list.
 * Returns 422 `storagePlaceNodeCyclicParent` (field: `parentNodeId`) if the new parent is a descendant of this node or the node itself.
 */
export const storagePlacesUpdateNodeMutation = (
  options?: Partial<Options<StoragePlacesUpdateNodeData>>,
): UseMutationOptions<
  StoragePlacesUpdateNodeResponse,
  StoragePlacesUpdateNodeError,
  Options<StoragePlacesUpdateNodeData>
> => {
  const mutationOptions: UseMutationOptions<
    StoragePlacesUpdateNodeResponse,
    StoragePlacesUpdateNodeError,
    Options<StoragePlacesUpdateNodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await storagePlacesUpdateNode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Bulk-update Order for a set of nodes.
 *
 * Body: `NodeOrderItem[]` — nodeId + order pairs.
 * Only the nodes included in the list are updated; others are unchanged.
 * Returns 422 `storagePlaceNodeNotFound` if any nodeId does not belong to this storage place.
 */
export const storagePlacesReorderNodesMutation = (
  options?: Partial<Options<StoragePlacesReorderNodesData>>,
): UseMutationOptions<
  StoragePlacesReorderNodesResponse,
  StoragePlacesReorderNodesError,
  Options<StoragePlacesReorderNodesData>
> => {
  const mutationOptions: UseMutationOptions<
    StoragePlacesReorderNodesResponse,
    StoragePlacesReorderNodesError,
    Options<StoragePlacesReorderNodesData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await storagePlacesReorderNodes({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Execute an atomic inventory transfer between two storage nodes.
 *
 * All items are moved in a single transaction — if any item fails, the entire transfer is rolled back.
 * Transfer type is determined by which field of each TransferItemRequest is populated:
 * `catalogItemId + count` → Standard; `unitItemId` → Unit; `assembledBundleItemId` → AssembledBundle.
 */
export const transfersExecuteMutation = (
  options?: Partial<Options<TransfersExecuteData>>,
): UseMutationOptions<
  TransfersExecuteResponse,
  TransfersExecuteError,
  Options<TransfersExecuteData>
> => {
  const mutationOptions: UseMutationOptions<
    TransfersExecuteResponse,
    TransfersExecuteError,
    Options<TransfersExecuteData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await transfersExecute({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersGetAllQueryKey = (options?: Options<UsersGetAllData>) =>
  createQueryKey("usersGetAll", options);

/**
 * List all users (paginated).
 */
export const usersGetAllOptions = (options?: Options<UsersGetAllData>) =>
  queryOptions<
    UsersGetAllResponse,
    UsersGetAllError,
    UsersGetAllResponse,
    ReturnType<typeof usersGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await usersGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersGetAllQueryKey(options),
  });

export const usersGetAllInfiniteQueryKey = (
  options?: Options<UsersGetAllData>,
): QueryKey<Options<UsersGetAllData>> => createQueryKey("usersGetAll", options, true);

/**
 * List all users (paginated).
 */
export const usersGetAllInfiniteOptions = (options?: Options<UsersGetAllData>) =>
  infiniteQueryOptions<
    UsersGetAllResponse,
    UsersGetAllError,
    InfiniteData<UsersGetAllResponse>,
    QueryKey<Options<UsersGetAllData>>,
    number | Pick<QueryKey<Options<UsersGetAllData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<UsersGetAllData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const {data} = await usersGetAll({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: usersGetAllInfiniteQueryKey(options),
    },
  );

/**
 * Create a new user.
 */
export const usersCreateMutation = (
  options?: Partial<Options<UsersCreateData>>,
): UseMutationOptions<UsersCreateResponse, UsersCreateError, Options<UsersCreateData>> => {
  const mutationOptions: UseMutationOptions<
    UsersCreateResponse,
    UsersCreateError,
    Options<UsersCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await usersCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a user.
 */
export const usersDeleteMutation = (
  options?: Partial<Options<UsersDeleteData>>,
): UseMutationOptions<UsersDeleteResponse, UsersDeleteError, Options<UsersDeleteData>> => {
  const mutationOptions: UseMutationOptions<
    UsersDeleteResponse,
    UsersDeleteError,
    Options<UsersDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await usersDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const usersGetByIdQueryKey = (options: Options<UsersGetByIdData>) =>
  createQueryKey("usersGetById", options);

/**
 * Get a user by ID.
 */
export const usersGetByIdOptions = (options: Options<UsersGetByIdData>) =>
  queryOptions<
    UsersGetByIdResponse,
    UsersGetByIdError,
    UsersGetByIdResponse,
    ReturnType<typeof usersGetByIdQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await usersGetById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: usersGetByIdQueryKey(options),
  });

/**
 * Update a user's profile, roles, and direct permissions atomically.
 */
export const usersUpdateMutation = (
  options?: Partial<Options<UsersUpdateData>>,
): UseMutationOptions<UsersUpdateResponse, UsersUpdateError, Options<UsersUpdateData>> => {
  const mutationOptions: UseMutationOptions<
    UsersUpdateResponse,
    UsersUpdateError,
    Options<UsersUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await usersUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reset another user's password (admin action, no current password required).
 */
export const usersChangePasswordMutation = (
  options?: Partial<Options<UsersChangePasswordData>>,
): UseMutationOptions<
  UsersChangePasswordResponse,
  UsersChangePasswordError,
  Options<UsersChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    UsersChangePasswordResponse,
    UsersChangePasswordError,
    Options<UsersChangePasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await usersChangePassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const warehousesGetAllQueryKey = (options?: Options<WarehousesGetAllData>) =>
  createQueryKey("warehousesGetAll", options);

/**
 * List all warehouses (paginated, optionally filtered by name).
 *
 * Query params: `page` (default 1), `pageSize` (default 20, max 200), `searchString` (optional).
 * Returns `Paginated&lt;WarehouseSummaryDto&gt;` — id, name, width, height, storagePlaceCount.
 * Requires `warehouses.view` (all warehouses) or `warehouses.view_assigned` (assigned warehouses only).
 */
export const warehousesGetAllOptions = (options?: Options<WarehousesGetAllData>) =>
  queryOptions<
    WarehousesGetAllResponse,
    WarehousesGetAllError,
    WarehousesGetAllResponse,
    ReturnType<typeof warehousesGetAllQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await warehousesGetAll({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: warehousesGetAllQueryKey(options),
  });

export const warehousesGetAllInfiniteQueryKey = (
  options?: Options<WarehousesGetAllData>,
): QueryKey<Options<WarehousesGetAllData>> => createQueryKey("warehousesGetAll", options, true);

/**
 * List all warehouses (paginated, optionally filtered by name).
 *
 * Query params: `page` (default 1), `pageSize` (default 20, max 200), `searchString` (optional).
 * Returns `Paginated&lt;WarehouseSummaryDto&gt;` — id, name, width, height, storagePlaceCount.
 * Requires `warehouses.view` (all warehouses) or `warehouses.view_assigned` (assigned warehouses only).
 */
export const warehousesGetAllInfiniteOptions = (options?: Options<WarehousesGetAllData>) =>
  infiniteQueryOptions<
    WarehousesGetAllResponse,
    WarehousesGetAllError,
    InfiniteData<WarehousesGetAllResponse>,
    QueryKey<Options<WarehousesGetAllData>>,
    number | Pick<QueryKey<Options<WarehousesGetAllData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<WarehousesGetAllData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const {data} = await warehousesGetAll({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: warehousesGetAllInfiniteQueryKey(options),
    },
  );

/**
 * Create a new warehouse with optional storage places.
 *
 * Body: `CreateWarehouseRequest` — name (required), width, height, storagePlaces (optional).
 */
export const warehousesCreateMutation = (
  options?: Partial<Options<WarehousesCreateData>>,
): UseMutationOptions<
  WarehousesCreateResponse,
  WarehousesCreateError,
  Options<WarehousesCreateData>
> => {
  const mutationOptions: UseMutationOptions<
    WarehousesCreateResponse,
    WarehousesCreateError,
    Options<WarehousesCreateData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await warehousesCreate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a warehouse and all its storage places.
 *
 * Returns 409 `warehouseHasItems` if the warehouse contains any stored items.
 * Requires `warehouses.edit` or `warehouses.edit_assigned` (assigned warehouses only).
 */
export const warehousesDeleteMutation = (
  options?: Partial<Options<WarehousesDeleteData>>,
): UseMutationOptions<
  WarehousesDeleteResponse,
  WarehousesDeleteError,
  Options<WarehousesDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    WarehousesDeleteResponse,
    WarehousesDeleteError,
    Options<WarehousesDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await warehousesDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const warehousesGetByIdQueryKey = (options: Options<WarehousesGetByIdData>) =>
  createQueryKey("warehousesGetById", options);

/**
 * Get a warehouse by ID including its storage places.
 */
export const warehousesGetByIdOptions = (options: Options<WarehousesGetByIdData>) =>
  queryOptions<
    WarehousesGetByIdResponse,
    WarehousesGetByIdError,
    WarehousesGetByIdResponse,
    ReturnType<typeof warehousesGetByIdQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await warehousesGetById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: warehousesGetByIdQueryKey(options),
  });

/**
 * Update a warehouse and atomically sync its storage places.
 *
 *     Body: `UpdateWarehouseRequest`. Storage place sync rules:
 * * id: null — create new storage place
 * * id present — update existing storage place
 * * existing storage place not in the list — delete
 * Returns 422 `storagePlaceNotFound` if any provided ID does not belong to this warehouse.
 * Requires `warehouses.edit` or `warehouses.edit_assigned` (assigned warehouses only).
 */
export const warehousesUpdateMutation = (
  options?: Partial<Options<WarehousesUpdateData>>,
): UseMutationOptions<
  WarehousesUpdateResponse,
  WarehousesUpdateError,
  Options<WarehousesUpdateData>
> => {
  const mutationOptions: UseMutationOptions<
    WarehousesUpdateResponse,
    WarehousesUpdateError,
    Options<WarehousesUpdateData>
  > = {
    mutationFn: async (fnOptions) => {
      const {data} = await warehousesUpdate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const warehousesGetByIdForPrintQueryKey = (
  options: Options<WarehousesGetByIdForPrintData>,
) => createQueryKey("warehousesGetByIdForPrint", options);

/**
 * Get all storage place nodes for a warehouse mapped to id + full path name for printing.
 */
export const warehousesGetByIdForPrintOptions = (options: Options<WarehousesGetByIdForPrintData>) =>
  queryOptions<
    WarehousesGetByIdForPrintResponse,
    WarehousesGetByIdForPrintError,
    WarehousesGetByIdForPrintResponse,
    ReturnType<typeof warehousesGetByIdForPrintQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await warehousesGetByIdForPrint({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: warehousesGetByIdForPrintQueryKey(options),
  });

export const warehousesGetDefaultNodeQueryKey = (options: Options<WarehousesGetDefaultNodeData>) =>
  createQueryKey("warehousesGetDefaultNode", options);

/**
 * Get the default storage place node for a warehouse.
 *
 * Returns 404 `warehouseNotFound` if the warehouse does not exist, or 404 `storagePlaceNodeNotFound` if no default node is set.
 */
export const warehousesGetDefaultNodeOptions = (options: Options<WarehousesGetDefaultNodeData>) =>
  queryOptions<
    WarehousesGetDefaultNodeResponse,
    WarehousesGetDefaultNodeError,
    WarehousesGetDefaultNodeResponse,
    ReturnType<typeof warehousesGetDefaultNodeQueryKey>
  >({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await warehousesGetDefaultNode({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: warehousesGetDefaultNodeQueryKey(options),
  });
