import type {PermissionName} from "@/api";

const permissionLabels: Record<PermissionName, string> = {
  "users.view": "Просмотр пользователей",
  "users.create": "Создание пользователей",
  "users.edit_profile": "Редактирование профиля",
  "users.delete": "Удаление пользователей",
  "users.manage_roles_and_permissions": "Управление ролями и правами",
  "users.manage_assigned_warehouses": "Управление назначенными складами",
  "users.reset_password": "Сброс пароля",
  "roles.view": "Просмотр ролей",
  "roles.edit": "Редактирование ролей",
  "catalog.view": "Просмотр каталога",
  "catalog.edit": "Редактирование каталога",
  "warehouses.view": "Просмотр всех складов",
  "warehouses.edit": "Редактирование всех складов",
  "warehouses.view_assigned": "Просмотр назначенных складов",
  "warehouses.edit_assigned": "Редактирование назначенных складов",
  "changelog.view": "Просмотр списка изменений",
  "receipts.view": "Просмотр всех приемок",
  "receipts.edit": "Редактирование всех приемок",
  "receipts.view_assigned": "Просмотр приемок назначенных складов",
  "receipts.edit_assigned": "Редактирование приемок назначенных складов",
  "receipts.process_assigned": "Обработка приемок назначенных складов",
  "transfers.execute": "Перемещение товаров (все склады)",
  "transfers.execute_assigned": "Перемещение товаров (назначенные склады)",
  "writeoffs.view": "Просмотр всех списаний",
  "writeoffs.edit": "Редактирование всех списаний",
  "writeoffs.view_assigned": "Просмотр списаний назначенных складов",
  "writeoffs.edit_assigned": "Редактирование списаний назначенных складов",
  "stocktakes.view": "Просмотр всех инвентаризаций",
  "stocktakes.edit": "Редактирование всех инвентаризаций",
  "stocktakes.view_assigned": "Просмотр инвентаризаций назначенных складов",
  "stocktakes.edit_assigned": "Редактирование инвентаризаций назначенных складов",
  "orders.view": "Просмотр всех заказов",
  "orders.edit": "Редактирование всех заказов",
  "orders.view_assigned": "Просмотр заказов назначенных складов",
  "orders.edit_assigned": "Редактирование заказов назначенных складов",
  "orders.assemble_assigned": "Сборка заказов назначенных складов",
  "orders.self_assign": "Взять заказ на себя",
  "integrations.view": "Просмотр интеграций с маркетплейсами",
  "integrations.edit": "Управление подключениями маркетплейсов",
  "integrations.map": "Сопоставление складов и карточек маркетплейсов",
  "integrations.sync": "Запуск синхронизации маркетплейсов",
  "statistics.view": "Просмотр статистики по всем складам",
  "statistics.view_assigned": "Просмотр статистики назначенных складов",
  "system.view": "Просмотр системных показателей и хранилища",
};

export function getPermissionLabel(permission: PermissionName | string): string {
  return permissionLabels[permission as PermissionName] ?? permission;
}
